(() => {
  "use strict";

  const EVENT_GOLD=Object.freeze({base:50,perLevel:20,sourceMultiplier:Object.freeze({talentRank:.35,heavyPurse:.70,slotPair:1,slotJackpot:1.6,slotPity:.25,wheel:1.25})});
  const adventurerLevel=level=>Math.max(1,Math.floor(Number(level)||1));
  const baseGold=level=>EVENT_GOLD.base+EVENT_GOLD.perLevel*adventurerLevel(level);
  function goldBaseFor(source,level,multiplier=1){const sourceMultiplier=EVENT_GOLD.sourceMultiplier[source];if(!Number.isFinite(sourceMultiplier))throw new Error(`Unknown event-Gold source: ${source}`);return Math.max(1,Math.round(baseGold(level)*sourceMultiplier*Math.max(0,Number(multiplier)||0)));}
  function roadTileCutoffs(board){return Number(board)>=5?Object.freeze({enemy:.75,slot:.82,treasure:.98}):Object.freeze({enemy:.72,slot:.80,treasure:.98});}
  function roadTileType(roll,board){const c=roadTileCutoffs(board),v=Number(roll)||0;return v<c.enemy?"enemy":v<c.slot?"event":v<c.treasure?"treasure":"empty";}
  function slotMatchOdds(luck=0){const v=Math.max(0,Number(luck)||0);return Object.freeze({secondMatch:Math.min(.78,.30+v),tripleFromPair:Math.min(.88,.42+v),pairFromMiss:Math.min(.72,.30+v*.55)});}
  window.DiceboundEventRewards=Object.freeze({apiVersion:1,gold:EVENT_GOLD,adventurerLevel,baseGold,goldBaseFor,roadTileCutoffs,roadTileType,slotMatchOdds});

  // Beta 0.6.4.3/0.6.4.4 browser presentation adapters. Gameplay ownership
  // stays in the extracted domain modules / compatibility runtime.
  function bridgeHeavyPurse(){
    if(Object.prototype.hasOwnProperty.call(window,"DiceboundPowerupRegistry"))return;
    Object.defineProperty(window,"DiceboundPowerupRegistry",{configurable:true,enumerable:true,get(){return undefined;},set(value){
      const base=value,wrapped=Object.freeze({...base,createRegistry(services){
        const list=base.createRegistry(services),purse=list.find(x=>x?.id==="purse");
        if(purse){const player=services.run.player,pay=services.economy.goldReward,raw=()=>goldBaseFor("heavyPurse",player.level);Object.defineProperty(purse,"desc",{configurable:true,enumerable:true,get(){return `Gain ${pay(raw())} gold now. Scales with Adventurer Level and Gold modifiers.`;}});purse.apply=()=>{player.gold+=pay(raw());};}
        return list;
      }});
      Object.defineProperty(window,"DiceboundPowerupRegistry",{configurable:true,enumerable:true,writable:true,value:wrapped});
    }});
  }

  function installBrowserPolish(){
    if(document.getElementById("db0643-hotfix-style"))return;
    const style=document.createElement("style");style.id="db0643-hotfix-style";style.textContent=`
#enemyIcon.db0636-tiered-enemy-stage .stage-enemy:has(.db0636-tiered-enemy-art[data-enemy-battle-art="devil"]){min-width:clamp(82px,13vw,175px)!important;min-height:clamp(145px,22vh,260px)!important}#enemyIcon.db0636-tiered-enemy-stage .stage-enemy:has(.db0636-tiered-enemy-art[data-enemy-battle-art="devil"]) .stage-sprite{width:min(15vw,180px)!important;height:clamp(140px,22vh,255px)!important}
#enemyIcon.enemy-stage-icons:has(.stage-enemy.guardian){min-height:clamp(285px,40vh,470px)!important;align-items:flex-end!important;justify-content:center!important;padding-top:34px!important;overflow:visible!important}#enemyIcon.enemy-stage-icons:has(.stage-enemy.guardian.final-boss){min-height:clamp(340px,47vh,560px)!important}.stage-enemy.guardian.miniboss{min-width:clamp(250px,26vw,390px)!important;min-height:clamp(270px,38vh,450px)!important;justify-content:flex-end!important}.stage-enemy.guardian.miniboss .stage-sprite{display:block!important;width:clamp(250px,26vw,390px)!important;height:clamp(250px,35vh,410px)!important;line-height:0!important}.stage-enemy.guardian.miniboss .enemy-art-frame{display:block!important;width:100%!important;height:100%!important;max-width:none!important;max-height:none!important;object-fit:contain!important;object-position:center bottom!important;border-radius:0!important}.stage-enemy.guardian.final-boss{min-width:clamp(320px,32vw,500px)!important;min-height:clamp(350px,46vh,540px)!important;justify-content:flex-end!important}.stage-enemy.guardian.final-boss .stage-sprite{display:block!important;width:clamp(320px,32vw,500px)!important;height:clamp(330px,43vh,510px)!important;line-height:0!important}.stage-enemy.guardian.final-boss .enemy-art-frame{display:block!important;width:100%!important;height:100%!important;max-width:none!important;max-height:none!important;object-fit:contain!important;object-position:center bottom!important;border-radius:0!important}
.app-tooltip-layer.db0643-gear{width:min(360px,calc(100vw - 18px));max-width:360px!important;padding:0!important;border:1px solid rgba(245,200,91,.38)!important;border-radius:12px!important;background:linear-gradient(180deg,#101827,#070b12)!important;box-shadow:0 18px 60px rgba(0,0,0,.76)!important;overflow:hidden}.db0643-head{display:grid;grid-template-columns:54px 1fr;gap:10px;align-items:center;padding:11px 12px 9px;border-bottom:1px solid rgba(255,255,255,.09)}.db0643-art{width:52px;height:52px;object-fit:contain}.db0643-name{font-size:15px;font-weight:950}.db0643-meta{font-size:10px;color:#aab5cb;margin-top:4px;text-transform:uppercase;letter-spacing:.06em}.db0643-name.poor{color:#b9bec8}.db0643-name.uncommon{color:#62d79a}.db0643-name.rare{color:#65a9ff}.db0643-name.epic{color:#b58cff}.db0643-name.legendary{color:#f5c85b}.db0643-name.mythical{color:#ff87e7}.db0643-name.artifact{color:#ff9d68}.db0643-stats{display:grid;padding:8px 12px 10px}.db0643-row{padding:4px 0;border-bottom:1px solid rgba(255,255,255,.05);font-size:11px;font-weight:750}.db0643-row:last-child{border-bottom:0}.db0643-row.special{color:#ffe4a0;margin-top:4px;border-top:1px solid rgba(245,200,91,.18)}.loot-bonuses.db0643-lines,.db0643-lines{display:grid!important;gap:3px!important}.db0643-line{display:block;padding:3px 0;border-bottom:1px solid rgba(255,255,255,.06)}
#lootOverlay .modal:has(.db0643-loot-compare){width:min(94vw,920px)!important;max-width:920px!important}#lootCard:has(.db0643-loot-compare){background:transparent!important;border:0!important;padding:0!important}.db0643-loot-compare{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:14px;align-items:stretch}.db0643-loot-side{min-width:0;padding:14px;border-radius:14px;border:1px solid rgba(255,255,255,.1);background:linear-gradient(180deg,rgba(18,28,46,.92),rgba(8,13,23,.94));box-shadow:inset 0 1px 0 rgba(255,255,255,.04)}.db0643-loot-found{border-color:rgba(245,200,91,.34)}.db0643-compare-title{font-size:10px;font-weight:950;text-transform:uppercase;letter-spacing:.11em;color:#aebbd1;margin-bottom:10px}.db0643-loot-found .db0643-compare-title{color:#f5c85b}.db0643-loot-side .loot-current{margin:0!important;padding:0!important;border:0!important;background:transparent!important}.db0643-loot-side .loot-icon{margin-inline:auto}.db0643-loot-side .loot-bonuses{margin-top:8px}.db0643-loot-side .loot-compare{margin-top:10px}
@media(max-width:799px){.db0643-loot-compare{grid-template-columns:1fr}.stage-enemy.guardian.miniboss{min-width:190px!important;min-height:210px!important}.stage-enemy.guardian.miniboss .stage-sprite{width:190px!important;height:200px!important}.stage-enemy.guardian.final-boss{min-width:250px!important;min-height:275px!important}.stage-enemy.guardian.final-boss .stage-sprite{width:250px!important;height:265px!important}}

/* Beta 0.6.4.4 lunch-playtest presentation follow-ups (#156). */
#enemyIcon.enemy-stage-icons:not(:has(.stage-enemy.guardian)){gap:clamp(10px,2.4vw,30px)!important;align-items:flex-end!important;justify-content:center!important;min-height:clamp(175px,27vh,285px)!important;overflow:visible!important}
#enemyIcon.enemy-stage-icons:not(:has(.stage-enemy.guardian)) .stage-enemy{flex:0 0 clamp(100px,11vw,150px)!important;width:clamp(100px,11vw,150px)!important;min-width:0!important;min-height:clamp(155px,23vh,235px)!important;justify-content:flex-end!important;align-items:center!important;overflow:visible!important}
#enemyIcon.enemy-stage-icons:not(:has(.stage-enemy.guardian)) .stage-sprite{display:flex!important;align-items:flex-end!important;justify-content:center!important;width:clamp(88px,9vw,128px)!important;height:clamp(105px,17vh,165px)!important;min-width:0!important;min-height:0!important;line-height:1!important;font-size:clamp(42px,5vw,66px)!important;overflow:visible!important}
#enemyIcon.enemy-stage-icons:not(:has(.stage-enemy.guardian)) .stage-sprite .enemy-art-frame,#enemyIcon.enemy-stage-icons:not(:has(.stage-enemy.guardian)) .stage-sprite .db0636-tiered-enemy-art{display:block!important;width:100%!important;height:100%!important;max-width:100%!important;max-height:100%!important;object-fit:contain!important;object-position:center bottom!important;margin:0 auto!important}
#enemyIcon.enemy-stage-icons:not(:has(.stage-enemy.guardian)) .target-arrow{margin-top:0!important;min-height:18px!important}
#lootOverlay .loot-actions{grid-template-columns:1fr!important;gap:8px!important}#lootOverlay .loot-actions .btn{width:100%!important}
.db0644-loot-delta{margin-top:13px;padding:11px 13px;border:1px solid rgba(123,198,255,.2);border-radius:11px;background:rgba(7,14,25,.82)}.db0644-delta-title{font-size:10px;font-weight:950;letter-spacing:.1em;text-transform:uppercase;color:#b8c7df;margin-bottom:7px}.db0644-delta-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:5px 10px}.db0644-delta-row{font-size:11px;font-weight:850;padding:4px 6px;border-radius:7px;background:rgba(255,255,255,.035)}.db0644-delta-row.up{color:#78e5a6}.db0644-delta-row.down{color:#ff8c96}.db0644-delta-none{font-size:11px;color:#aeb8ca;font-style:italic}
.board .tile.cleared:not(.merchant):not(.current)::before{content:"👣";position:absolute;left:50%;bottom:5px;z-index:5;transform:translateX(-50%) rotate(-14deg);font-size:clamp(11px,1vw,15px);line-height:1;opacity:.42;filter:grayscale(1) sepia(.55) brightness(1.25);pointer-events:none;text-shadow:0 1px 3px rgba(0,0,0,.65)}
@media(max-width:799px){.db0644-delta-grid{grid-template-columns:1fr}}
`;document.head.appendChild(style);

    const rarityIds=["poor","common","uncommon","rare","epic","legendary","mythical","artifact","omega"],statRe=/^([+−-]?\d+(?:\.\d+)?%?)\s+(.+)$/;
    const esc=v=>String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
    const numberText=value=>{const a=Math.abs(value);return Number.isInteger(a)?String(a):a.toFixed(2).replace(/0+$/,"").replace(/\.$/,"");};
    function parse(raw){const parts=String(raw||"").replace(/\+\-/g,"-").replace(/\s*·\s*INTRINSIC\s*\([^)]*\)\s*:\s*/gi," · ").replace(/\s*INTRINSIC\s*\([^)]*\)\s*:\s*/gi,"").split(/\s*·\s*/).map(x=>x.trim()).filter(Boolean),map=new Map(),order=[],special=[];for(const part of parts){if(/^No bonuses$/i.test(part))continue;if(/^(Unique:|Set:|Element:|Fire|Ice|Electric|Light|Void|Nature|Donut|Tech|Metal|Coffee|Gun|Radiation)\b/i.test(part)){special.push(part);continue;}const m=part.match(statRe);if(!m){special.push(part);continue;}const rv=m[1].replace("−","-"),pct=rv.endsWith("%"),val=Number(rv.replace("%","")),label=m[2].trim(),key=`${pct?"%":"n"}:${label.toLowerCase()}`;if(!Number.isFinite(val)){special.push(part);continue;}if(!map.has(key))order.push(key);const e=map.get(key)||{value:0,pct,label,key};e.value+=val;map.set(key,e);}const values=order.map(k=>map.get(k));return{values,stats:values.map(e=>`${e.value>=0?"+":"−"}${numberText(e.value)}${e.pct?"%":""} ${e.label}`),special};}
    const rows=p=>[...p.stats,...p.special].map(v=>`<span class="db0643-line">${esc(v)}</span>`).join("")||'<span class="db0643-line">No bonuses</span>';
    function statDelta(found=[],current=[]){const map=new Map(),order=[];for(const entry of current){map.set(entry.key,{...entry,value:-entry.value});order.push(entry.key);}for(const entry of found){if(!map.has(entry.key)){map.set(entry.key,{...entry,value:0});order.push(entry.key);}map.get(entry.key).value+=entry.value;}return order.map(k=>map.get(k)).filter(e=>Math.abs(e.value)>.0001);}
    function deltaMarkup(found,current){const delta=statDelta(found,current);if(!delta.length)return'<div class="db0644-delta-none">No numeric stat change.</div>';return`<div class="db0644-delta-grid">${delta.map(e=>`<div class="db0644-delta-row ${e.value>0?"up":"down"}">${e.value>0?"+":"−"}${numberText(e.value)}${e.pct?"%":""} ${esc(e.label)}</div>`).join("")}</div>`;}
    function compareLoot(){const card=document.getElementById("lootCard"),current=card?.querySelector?.(".loot-current");if(!card||!current||card.querySelector(":scope > .db0643-loot-compare"))return;const foundBonuses=card.querySelector(".loot-bonuses"),found=parse(foundBonuses?.dataset.db0644Raw||foundBonuses?.textContent||"").values,currentParsed=parse(current.dataset.db0644Raw||"").values;current.remove();const grid=document.createElement("div"),equipped=document.createElement("section"),foundSide=document.createElement("section"),equippedTitle=document.createElement("div"),foundTitle=document.createElement("div"),delta=document.createElement("div");grid.className="db0643-loot-compare";equipped.className="db0643-loot-side db0643-loot-equipped";foundSide.className="db0643-loot-side db0643-loot-found";equippedTitle.className=foundTitle.className="db0643-compare-title";equippedTitle.textContent="Currently equipped";foundTitle.textContent="New equipment";while(card.firstChild)foundSide.appendChild(card.firstChild);equipped.append(equippedTitle,current);foundSide.prepend(foundTitle);grid.append(equipped,foundSide);delta.className="db0644-loot-delta";delta.innerHTML=`<div class="db0644-delta-title">Stat changes if equipped</div>${deltaMarkup(found,currentParsed)}`;card.append(grid,delta);}
    function enhance(){document.querySelectorAll("#equipmentGrid .equipment-slot:not(.empty)").forEach(slot=>{const title=slot.getAttribute("title");if(title&&!slot.dataset.db0643Raw)slot.dataset.db0643Raw=title;const raw=slot.dataset.db0643Raw||"",i=raw.indexOf(":"),name=i>=0?raw.slice(0,i).trim():slot.querySelector(".slot-item span")?.textContent?.trim()||"Equipment",p=parse(i>=0?raw.slice(i+1):""),rarity=rarityIds.find(x=>slot.classList.contains(x))||"common";Object.assign(slot.dataset,{db0643Name:name,db0643Rarity:rarity,db0643Stats:JSON.stringify(p.stats),db0643Special:JSON.stringify(p.special),tooltip:"equipment"});slot.removeAttribute("title");});document.querySelectorAll(".loot-bonuses:not([data-db0643])").forEach(n=>{const raw=n.textContent||"";n.dataset.db0643="1";n.dataset.db0644Raw=raw;n.classList.add("db0643-lines");n.innerHTML=rows(parse(raw));});document.querySelectorAll(".loot-current:not([data-db0643])").forEach(n=>{const t=n.textContent||"";n.dataset.db0644Raw=t.includes("—")?t.slice(t.indexOf("—")+1):"";if(!/Currently equipped:/i.test(t)||!t.includes("—")){n.dataset.db0643="1";return;}const name=n.querySelector("b")?.textContent?.trim()||"Current item";n.dataset.db0643="1";n.innerHTML=`<div><b>${esc(name)}</b></div><div class="db0643-lines">${rows(parse(n.dataset.db0644Raw))}</div>`;});document.querySelectorAll(".shop-item-desc:not([data-db0643])").forEach(n=>{const t=n.textContent||"";if(!/INTRINSIC/i.test(t))return;const parts=t.split(/\s*·\s*/),slot=parts.shift()||"Equipment";n.dataset.db0643="1";n.innerHTML=`<strong>${esc(slot)}</strong><div class="db0643-lines">${rows(parse(parts.join(" · ")))}</div>`;});document.querySelectorAll("[title],[data-tip],[data-tooltip]").forEach(n=>{for(const a of ["title","data-tip","data-tooltip"]){const v=n.getAttribute(a);if(v&&/INTRINSIC/i.test(v))n.setAttribute(a,v.replace(/\s*·?\s*INTRINSIC\s*\([^)]*\)\s*:\s*/gi," · ").replace(/\+\-/g,"-"));}});compareLoot();}
    function tooltip(slot){const layer=document.getElementById("appTooltipLayer");if(!layer)return;const rarity=slot.dataset.db0643Rarity||"common",name=slot.dataset.db0643Name||"Equipment",meta=`${rarity} · ${slot.querySelector(".slot-label")?.textContent?.trim()||"Equipment"}`,art=slot.querySelector("img")?.getAttribute("src")||"";let stats=[],special=[];try{stats=JSON.parse(slot.dataset.db0643Stats||"[]");special=JSON.parse(slot.dataset.db0643Special||"[]");}catch(_){}layer.classList.add("db0643-gear");layer.innerHTML=`<div class="db0643-head">${art?`<img class="db0643-art" src="${esc(art)}" alt="">`:"<span></span>"}<div><div class="db0643-name ${rarity}">${esc(name)}</div><div class="db0643-meta">${esc(meta)}</div></div></div><div class="db0643-stats">${stats.map(v=>`<div class="db0643-row">${esc(v)}</div>`).join("")}${special.map(v=>`<div class="db0643-row special">${esc(v)}</div>`).join("")}</div>`;layer.classList.remove("hidden");const r=slot.getBoundingClientRect(),tr=layer.getBoundingClientRect(),g=10,m=8;let left=r.right+g,top=r.top;if(left+tr.width>innerWidth-m)left=r.left-tr.width-g;left=Math.max(m,Math.min(innerWidth-tr.width-m,left));top=Math.max(m,Math.min(innerHeight-tr.height-m,top));layer.style.left=`${Math.round(left)}px`;layer.style.top=`${Math.round(top)}px`;}
    document.addEventListener("pointerover",e=>{const slot=e.target?.closest?.("#equipmentGrid .equipment-slot[data-db0643-name]"),layer=document.getElementById("appTooltipLayer");if(slot)tooltip(slot);else layer?.classList.remove("db0643-gear");});document.addEventListener("focusin",e=>{const slot=e.target?.closest?.("#equipmentGrid .equipment-slot[data-db0643-name]");if(slot)tooltip(slot);});

    const observer=new MutationObserver(enhance);observer.observe(document.body,{childList:true,subtree:true});enhance();window.DiceboundLunchHotfixTest=Object.freeze({parse,statDelta,enhance,compareLoot,heavyPurseBase:level=>goldBaseFor("heavyPurse",level)});
  }

  bridgeHeavyPurse();if(typeof document!=="undefined")setTimeout(installBrowserPolish,0);
})();
