from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
MONOLITH=ROOT/'runtime/js/dicebound.js'


def replace_once(text:str,old:str,new:str,label:str)->str:
    if old in text:
        return text.replace(old,new,1)
    if new in text:
        return text
    raise RuntimeError(f'{label} shape changed unexpectedly')


def remove_once(text:str,old:str,label:str)->str:
    if old in text:
        return text.replace(old,'',1)
    return text


def main()->int:
    text=MONOLITH.read_text(encoding='utf-8')
    before=text.count('\n')+1

    # Collapse the two historical dodge wrappers into the one behavior that is
    # actually shipped: base diminishing dodge -> Monk hook -> identity hook.
    text=replace_once(
        text,
        'function effectiveDodgeChance(){const raw=rawDodgeChance();return raw/(1+raw);}',
        'function effectiveDodgeChance(){const raw=rawDodgeChance(),base=raw/(1+raw);return dbClasses.identityDodgeAdjustments(dbClasses.legacyMonkDodge(base));}',
        'effectiveDodgeChance canonical body',
    )
    text=remove_once(text,'  const effectiveDodgeChanceV12=effectiveDodgeChance;\n  effectiveDodgeChance=function(){return dbClasses.legacyMonkDodge(effectiveDodgeChanceV12());};\n','effectiveDodgeChance V12 wrapper')
    text=remove_once(text,'  const effectiveDodgeChanceV13=effectiveDodgeChance;\n  effectiveDodgeChance=function(){return dbClasses.identityDodgeAdjustments(effectiveDodgeChanceV13());};\n','effectiveDodgeChance V13 wrapper')

    # The final shipped Heirloom capacity completely superseded the run-snapshot
    # wrapper. Keep that final rule once, at its original canonical declaration.
    text=replace_once(
        text,
        'function getHeirloomSlots(){return 1+talentRank("legacy_heirloom")+((meta.prestige?.count||0)>=20?1:0);}',
        'function getHeirloomSlots(){return 1+talentRank("legacy_heirloom")+((meta.prestige?.count||0)>=20?1:0)+((meta.prestige?.count||0)>=60?1:0);}',
        'getHeirloomSlots canonical body',
    )
    text=remove_once(text,'  const getHeirloomSlotsV15=getHeirloomSlots;getHeirloomSlots=function(){const source=runTalentSnapshot;if(!source)return getHeirloomSlotsV15();return 1+(Number(source.legacy_heirloom)||0)+((meta.prestige?.count||0)>=20?1:0);};\n','getHeirloomSlots V15 wrapper')
    text=remove_once(text,'  // ---- Heirloom slot capacity retained after V27 Prestige no-choice flow --\n  getHeirloomSlots=function(){return 1+talentRank("legacy_heirloom")+((meta.prestige?.count||0)>=20?1:0)+((meta.prestige?.count||0)>=60?1:0);};\n','getHeirloomSlots final overwrite')

    # Seed parsing is one current parser, not a current parser which falls back
    # into its historical predecessor. Legendary is intentionally included: it
    # is still generated by the current Legendary item path.
    text=replace_once(
        text,
        'function v15SafeClassId(id){return CLASSES[id]?id:"ranger";}',
        'function v15SafeClassId(id){if(!CLASSES[id])throw new Error(`Unknown equipment seed class: ${id}`);return id;}',
        'strict equipment seed class',
    )
    historical_parser='''  // Accept the complete current ordinary-rarity ladder in item seed codes.\n  // Fall back to the historical parser for old saved/hand-entered seed codes.\n  const v15ParseSeedCodeV251Historical=v15ParseSeedCode;\n  v15ParseSeedCode=function(code){\n    const m=String(code||'').trim().match(/^D15\\|(poor|common|uncommon|rare|epic)\\|(weapon|offhand|boots|legs|chest|hat|ring|amulet)\\|([a-z0-9_]+)\\|q(\\d+)\\|([a-z0-9_-]+)$/i);\n    if(!m)return v15ParseSeedCodeV251Historical(code);\n    return {rarity:m[1].toLowerCase(),slot:m[2].toLowerCase(),classId:v15SafeClassId(m[3].toLowerCase()),qualityBoost:clamp(Number(m[4])||0,0,8),core:m[5]};\n  };\n'''
    text=remove_once(text,historical_parser,'V2.5.1 historical seed parser fallback')

    # New saves have mode-qualified board-clear keys. The pre-mode key is an
    # old-save compatibility read and is intentionally retired in 0.6.7.0.
    text=remove_once(text,'  function legacyBoardClearKey(classId,board){return `${classId}:b${board}`;}\n','legacy board-clear key')
    text=replace_once(
        text,
        "function hasBoardClear(classId,board){ensureAlphaMeta();return Object.entries(meta.stats.boardClears).some(([key,count])=>Number(count)>0&&(key===boardClearKey(classId,board,'normal')||key===boardClearKey(classId,board,'nightmare')||key===boardClearKey(classId,board,'hell')||key===legacyBoardClearKey(classId,board)));}",
        "function hasBoardClear(classId,board){ensureAlphaMeta();return Object.entries(meta.stats.boardClears).some(([key,count])=>Number(count)>0&&(key===boardClearKey(classId,board,'normal')||key===boardClearKey(classId,board,'nightmare')||key===boardClearKey(classId,board,'hell')));}",
        'mode-qualified board-clear lookup',
    )

    # Collapse the five-layer damage predecessor chain. Ordering is deliberate
    # and matches the shipped wrappers exactly: Ninja -> Berserker -> base hit ->
    # career accounting -> Croak/Endless Form post-hook.
    old_damage='''function damageEnemy(enemy,amount,ignoreDefense=false){if(!enemy||enemy.hp<=0)return 0;if(enemy.enemyBarrier>0&&!ignoreDefense){enemy.enemyBarrier--;addCombatHistory(`${enemy.name}'s merchant barrier cancels the hit. ${enemy.enemyBarrier} remain.`);return 0;}const raw=Math.max(0,Math.round(amount)),actual=Math.max(raw>0?1:0,raw-(ignoreDefense?0:(enemy.defense||0))),dealt=Math.min(enemy.hp,actual);enemy.hp-=dealt;return dealt;}'''
    new_damage='''function damageEnemy(enemy,amount,ignoreDefense=false){\n    const adjusted=dbClasses.ninjaExecutionDamage(amount,ignoreDefense);amount=dbClasses.berserkerDamage(adjusted.amount);ignoreDefense=adjusted.ignoreDefense;let dealt=0;\n    if(enemy&&enemy.hp>0){if(enemy.enemyBarrier>0&&!ignoreDefense){enemy.enemyBarrier--;addCombatHistory(`${enemy.name}'s merchant barrier cancels the hit. ${enemy.enemyBarrier} remain.`);}else{const raw=Math.max(0,Math.round(amount)),actual=Math.max(raw>0?1:0,raw-(ignoreDefense?0:(enemy.defense||0)));dealt=Math.min(enemy.hp,actual);enemy.hp-=dealt;}}\n    if(gameStarted&&dealt>0)ensureAlphaMeta().damageDealt+=dealt;\n    if(player._v25CroakHitsRemaining>0){player._v25CroakHitsRemaining--;const rank=dbProgression.gameplayTalentRank('monk_flow_ceiling'),chance=rank*.05;if(enemy?.hp>0&&rank>0&&random()<chance){enemy.poisonStacks=(enemy.poisonStacks||0)+1;addCombatHistory(`🐸☠️ Croak Cascade leaves 1 Poison stack (${Math.round(chance*100)}% from Endless Form rank ${rank}).`);}}\n    return dealt;\n  }'''
    text=replace_once(text,old_damage,new_damage,'damageEnemy canonical body')
    for label,block in [
        ('damageEnemy V12','  const damageEnemyV12=damageEnemy;\n  damageEnemy=function(enemy,amount,ignoreDefense=false){return damageEnemyV12(enemy,dbClasses.berserkerDamage(amount),ignoreDefense);};\n'),
        ('damageEnemy V13','  const damageEnemyV13=damageEnemy;\n  damageEnemy=function(enemy,amount,ignoreDefense=false){const adjusted=dbClasses.ninjaExecutionDamage(amount,ignoreDefense);return damageEnemyV13(enemy,adjusted.amount,adjusted.ignoreDefense);};\n'),
        ('damageEnemy V15','  // Lifetime damage is measured centrally so pets, poison, elements, basic hits and ultimates all count.\n  const damageEnemyV15=damageEnemy;damageEnemy=function(enemy,amount,ignoreDefense=false){const dealt=damageEnemyV15(enemy,amount,ignoreDefense);if(gameStarted&&dealt>0){ensureAlphaMeta().damageDealt+=dealt;}return dealt;};\n'),
        ('damageEnemy V25 Croak','''  // Endless Form makes Croak Cascade poisonous: each jump gets an independent\n  // 5% chance per Endless Form rank to leave one Poison stack.\n  const damageEnemyV25CroakBase=damageEnemy;\n  damageEnemy=function(enemy,amount,ignoreDefense=false){\n    const dealt=damageEnemyV25CroakBase(enemy,amount,ignoreDefense);\n    if(player._v25CroakHitsRemaining>0){player._v25CroakHitsRemaining--;const rank=dbProgression.gameplayTalentRank('monk_flow_ceiling'),chance=rank*.05;if(enemy?.hp>0&&rank>0&&random()<chance){enemy.poisonStacks=(enemy.poisonStacks||0)+1;addCombatHistory(`🐸☠️ Croak Cascade leaves 1 Poison stack (${Math.round(chance*100)}% from Endless Form rank ${rank}).`);}}\n    return dealt;\n  };\n'''),
    ]:
        text=remove_once(text,block,label)

    forbidden=(
        'effectiveDodgeChanceV12','effectiveDodgeChanceV13','getHeirloomSlotsV15',
        'v15ParseSeedCodeV251Historical','legacyBoardClearKey','damageEnemyV12',
        'damageEnemyV13','damageEnemyV15','damageEnemyV25CroakBase',
    )
    survivors=[name for name in forbidden if name in text]
    if survivors:raise RuntimeError(f'canonical-wave predecessor survived: {survivors}')

    # Tidy the gaps left by predecessor blocks without compressing useful code.
    while '\n\n\n' in text:text=text.replace('\n\n\n','\n\n')
    MONOLITH.write_text(text,encoding='utf-8',newline='\n')
    after=text.count('\n')+1
    print(f'CANONICAL_0670_WAVE2 {before}->{after} lines; dodge 3->1; heirloom slots 3->1; damage 5->1; seed parser 2->1; legacy board key retired')
    return 0


if __name__=='__main__':raise SystemExit(main())
