"use strict";

const assert=require("node:assert/strict");
const childProcess=require("node:child_process");
const fs=require("node:fs");
const http=require("node:http");
const os=require("node:os");
const path=require("node:path");

const ROOT=path.join(__dirname,".."),RUNTIME=path.join(ROOT,"runtime");
const EDGE=process.env.DICEBOUND_EDGE||"C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe";
const DEBUG_PORT=Number(process.env.DICEBOUND_EDGE_DEBUG_PORT||19357);
const MEMORY_STRESS_CYCLES=Math.max(1,Math.min(12,Math.floor(Number(process.env.DICEBOUND_MEMORY_STRESS_CYCLES)||3)));
const MIME={".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".json":"application/json; charset=utf-8",".png":"image/png",".jpg":"image/jpeg",".jpeg":"image/jpeg",".webp":"image/webp",".wav":"audio/wav"};
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function fetchWithTimeout(url,timeout=1500){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{return await fetch(url,{signal:controller.signal});}finally{clearTimeout(timer);}}

function serveRuntime(){
  return new Promise((resolve,reject)=>{
    const server=http.createServer((request,response)=>{
      const pathname=decodeURIComponent(new URL(request.url,"http://127.0.0.1").pathname),relative=pathname==="/"?"index.html":pathname.replace(/^\/+/,"");
      const file=path.resolve(RUNTIME,relative);
      if(!file.startsWith(`${RUNTIME}${path.sep}`)&&file!==path.join(RUNTIME,"index.html")){response.writeHead(403).end();return;}
      fs.readFile(file,(error,data)=>{if(error){response.writeHead(404).end();return;}response.writeHead(200,{"Content-Type":MIME[path.extname(file).toLowerCase()]||"application/octet-stream","Cache-Control":"no-store"});response.end(data);});
    });
    server.once("error",reject);server.listen(0,"127.0.0.1",()=>resolve({server,url:`http://127.0.0.1:${server.address().port}/index.html`}));
  });
}
async function waitForJson(url,timeout=15000){
  const deadline=Date.now()+timeout;let last;
  while(Date.now()<deadline){try{const response=await fetchWithTimeout(url);if(response.ok)return response.json();last=new Error(`${response.status} ${response.statusText}`);}catch(error){last=error;}await sleep(100);}
  throw last||new Error(`Timed out waiting for ${url}`);
}
async function connectPage(expectedUrl){
  const origin=new URL(expectedUrl).origin,deadline=Date.now()+15000;let target=null;
  while(Date.now()<deadline&&!target){const targets=await waitForJson(`http://127.0.0.1:${DEBUG_PORT}/json/list`);target=targets.find(item=>item.type==="page"&&item.webSocketDebuggerUrl&&item.url.startsWith(origin));if(!target)await sleep(100);}
  if(!target)throw new Error("Edge did not expose a page target");
  const socket=new WebSocket(target.webSocketDebuggerUrl),pending=new Map(),events=[];let id=0;
  await new Promise((resolve,reject)=>{socket.addEventListener("open",resolve,{once:true});socket.addEventListener("error",reject,{once:true});});
  socket.addEventListener("message",event=>{const message=JSON.parse(String(event.data)),request=pending.get(message.id);if(!request){events.push(message);return;}pending.delete(message.id);clearTimeout(request.timer);message.error?request.reject(new Error(message.error.message)):request.resolve(message.result);});
  function send(method,params={}){return new Promise((resolve,reject)=>{const requestId=++id,timer=setTimeout(()=>{if(pending.delete(requestId))reject(new Error(`DevTools request timed out: ${method}`));},20000);pending.set(requestId,{resolve,reject,timer});socket.send(JSON.stringify({id:requestId,method,params}));});}
  async function evaluate(expression){const result=await send("Runtime.evaluate",{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw new Error(result.exceptionDetails.exception?.description||result.exceptionDetails.text);return result.result.value;}
  return {socket,send,evaluate,events};
}
async function launch(profile,url){
  const child=childProcess.spawn(EDGE,["--headless=new","--disable-gpu","--no-first-run","--no-default-browser-check","--remote-allow-origins=*",`--user-data-dir=${profile}`,`--remote-debugging-port=${DEBUG_PORT}`,url],{stdio:"ignore",windowsHide:true});
  const page=await connectPage(url);await page.send('Runtime.enable');await page.send('Log.enable');
  const deadline=Date.now()+20000;
  while(Date.now()<deadline){if(await page.evaluate("document.readyState==='complete'&&!!window.DiceboundRunResumeTest"))return {child,...page};await sleep(100);}
  const diagnostics=page.events.filter(event=>event.method==='Runtime.exceptionThrown'||event.method==='Log.entryAdded').map(event=>event.params?.exceptionDetails?.exception?.description||event.params?.exceptionDetails?.text||event.params?.entry?.text||event.method);throw new Error(`DiceBound runtime did not finish loading in Edge: ${diagnostics.join(' | ')}`);
}
async function closeEdge(edge){try{await Promise.race([edge.send("Browser.close"),sleep(750)]);}catch(_){}try{edge.socket.close();}catch(_){}if(edge.child.exitCode===null)await Promise.race([new Promise(resolve=>edge.child.once("exit",resolve)),sleep(5000)]);if(edge.child.exitCode===null)edge.child.kill();}
async function removeTempProfile(profile){for(let attempt=0;attempt<12;attempt+=1){try{fs.rmSync(profile,{recursive:true,force:true});return true;}catch(error){if(attempt===11){console.warn(`Edge smoke temporary profile remained locked: ${profile}`);return false;}await sleep(500);}}return false;}
async function captureClassChooserViewport(page,width,height){
  await page.send("Emulation.setDeviceMetricsOverride",{width,height,deviceScaleFactor:1,mobile:false});
  return page.evaluate(`(()=>{const panel=document.getElementById('campClassPanel');if(!panel?.classList.contains('active'))document.getElementById('campClassBtn')?.click();const roster=document.querySelector('.class-chooser-roster'),done=document.querySelector('[data-class-chooser-done]'),header=document.querySelector('.class-chooser-header p'),detail=document.querySelector('.class-detail-art img');if(!roster||!done)return {ready:false};const positions=[0,.5,1].map(progress=>{roster.scrollTop=Math.round(Math.max(0,roster.scrollHeight-roster.clientHeight)*progress);const rect=done.getBoundingClientRect();return {scrollTop:roster.scrollTop,visible:rect.top>=0&&rect.bottom<=innerHeight};});const rect=done.getBoundingClientRect();return {ready:true,width:innerWidth,height:innerHeight,panelActive:panel.classList.contains('active'),maxScroll:Math.max(0,roster.scrollHeight-roster.clientHeight),positions,donePosition:getComputedStyle(done).position,doneVisible:rect.top>=0&&rect.bottom<=innerHeight,headerDetail:getComputedStyle(header).display,detailArt:detail?.getAttribute('src')||null};})()`);
}
async function capturePetChooserViewport(page,width,height){
  await page.send("Emulation.setDeviceMetricsOverride",{width,height,deviceScaleFactor:1,mobile:false});
  return page.evaluate(`(()=>{const overlay=document.getElementById('petCollectionOverlay');if(overlay?.classList.contains('hidden'))document.getElementById('campPetBtn')?.click();const shell=overlay?.querySelector('.pet-chooser-shell'),header=overlay?.querySelector('.pet-chooser-chrome'),done=overlay?.querySelector('[data-pet-chooser-done]'),grid=overlay?.querySelector('[data-pet-chooser-grid]');if(!shell||!header||!done||!grid)return {ready:false};const positions=[0,.5,1].map(progress=>{shell.scrollTop=Math.round(Math.max(0,shell.scrollHeight-shell.clientHeight)*progress);const rect=done.getBoundingClientRect();return {scrollTop:shell.scrollTop,visible:rect.top>=0&&rect.bottom<=innerHeight};});const rect=done.getBoundingClientRect();return {ready:true,width:innerWidth,height:innerHeight,open:!overlay.classList.contains('hidden'),cards:grid.querySelectorAll('[data-pet-choice]').length,maxScroll:Math.max(0,shell.scrollHeight-shell.clientHeight),positions,headerPosition:getComputedStyle(header).position,doneVisible:rect.top>=0&&rect.bottom<=innerHeight};})()`);
}
async function captureTalentTreeViewport(page,width,height){
  await page.send("Emulation.setDeviceMetricsOverride",{width,height,deviceScaleFactor:1,mobile:false});
  return page.evaluate(`(()=>{const api=window.DiceboundTalentTree;if(!api)return {ready:false};api.open();const overlay=document.getElementById('talentOverlay'),view=overlay?.querySelector('[data-talent-viewport]'),done=overlay?.querySelector('[data-talent-done]'),header=overlay?.querySelector('.talent-tree-chrome'),label=overlay?.querySelector('[data-talent-zoom-label]'),nodes=overlay?.querySelectorAll('[data-talent-id]');if(!view||!done||!header||!label)return {ready:false};api.fit();const fitted=label.textContent;const positions=[0,.5,1].map(progress=>{view.scrollTop=Math.round(Math.max(0,view.scrollHeight-view.clientHeight)*progress);const rect=done.getBoundingClientRect();return {scrollTop:view.scrollTop,visible:rect.top>=0&&rect.bottom<=innerHeight};});const beforeWheel=label.textContent,rect=view.getBoundingClientRect();view.dispatchEvent(new WheelEvent('wheel',{deltaY:-120,clientX:rect.left+rect.width*.62,clientY:rect.top+rect.height*.38,bubbles:true,cancelable:true}));const afterWheel=label.textContent;api.setZoom(.28);const minZoom=label.textContent;api.setZoom(2.3);const maxZoom=label.textContent;api.fit();const doneRect=done.getBoundingClientRect();return {ready:true,width:innerWidth,height:innerHeight,open:!overlay.classList.contains('hidden'),nodes:nodes.length,maxScroll:Math.max(0,view.scrollHeight-view.clientHeight),positions,fitted,beforeWheel,afterWheel,minZoom,maxZoom,doneVisible:doneRect.top>=0&&doneRect.bottom<=innerHeight,headerOutsideScroller:!view.contains(done)};})()`);
}
async function capturePrestigeMoonViewport(page,width,height){
  await page.send("Emulation.setDeviceMetricsOverride",{width,height,deviceScaleFactor:1,mobile:false});
  return page.evaluate(`(()=>{const api=window.DiceboundPrestigeMoon;if(!api)return {ready:false};api.open();const overlay=document.getElementById('prestigeMoonOverlay'),back=overlay?.querySelector('[data-prestige-back]'),held=overlay?.querySelector('[data-prestige-held]'),tooltip=overlay?.querySelector('.prestige-held-tooltip'),action=overlay?.querySelector('[data-prestige-action]'),refund=overlay?.querySelector('[data-prestige-refund]'),nodes=[...overlay?.querySelectorAll?.('[data-prestige-node]')||[]];if(!overlay||!back||!held||!tooltip||!action||!refund)return {ready:false};held.focus();const rect=back.getBoundingClientRect(),nodeRects=nodes.map(node=>{const r=node.getBoundingClientRect();return {left:r.left,top:r.top,right:r.right,bottom:r.bottom};});return {ready:true,width:innerWidth,height:innerHeight,owner:api.inspect(),open:!overlay.classList.contains('hidden'),backPosition:getComputedStyle(back).position,backVisible:rect.top>=0&&rect.right<=innerWidth&&rect.bottom<=innerHeight,heldText:held.textContent,tooltipVisible:getComputedStyle(tooltip).display!=='none',actionText:action.textContent,actionDisabled:action.disabled,refundDisabled:refund.disabled,nodeCount:nodes.length,hasTopNode:nodes.some(node=>node.classList.contains('top')),forgeText:nodes.find(node=>node.dataset.prestigeNode==='moon-forge')?.textContent||'',nodeRects,nodesInViewport:nodeRects.every(r=>r.left>=-1&&r.top>=-1&&r.right<=innerWidth+1&&r.bottom<=innerHeight+1)};})()`);
}
async function captureCampViewport(page,width,height){
  await page.send("Emulation.setDeviceMetricsOverride",{width,height,deviceScaleFactor:1,mobile:false});
  return page.evaluate(`new Promise(resolve=>{window.DiceboundCamp?.refresh();setTimeout(()=>requestAnimationFrame(()=>requestAnimationFrame(()=>{const scene=document.getElementById('campScene'),stage=scene?.getBoundingClientRect(),ids=['campOptionsBtn','campTalentBtn','campMoonBtn','campInfoBtn','campNightmareBtn','campHellBtn','campClassBtn','campPetBtn','campChestBtn','campAchievementBtn','campGoBtn'];const objects=Object.fromEntries(ids.map(id=>{const node=document.getElementById(id),rect=node?.getBoundingClientRect(),style=node&&getComputedStyle(node);return [id,{present:!!node,visible:!!rect&&rect.width>0&&rect.height>0&&style.visibility!=='hidden'&&style.display!=='none',rect:rect?{left:Math.round(rect.left),top:Math.round(rect.top),width:Math.round(rect.width),height:Math.round(rect.height)}:null,position:style?.position||null,transform:style?.transform||null,translate:style?.translate||null,inlineTranslate:node?.style.getPropertyValue('translate')||null}]}));resolve({width:innerWidth,height:innerHeight,layout:scene?.dataset.dbCampLayout||null,stage:stage?{left:Math.round(stage.left),top:Math.round(stage.top),width:Math.round(stage.width),height:Math.round(stage.height)}:null,objects});})),260)})`);
}
function assertCampViewport(sample,label,layout){
  assert.equal(sample.layout,layout,`${label} Camp used the wrong layout regime`);assert.ok(sample.stage&&sample.stage.width>0&&sample.stage.height>0,`${label} Camp stage did not render`);assert.ok(Math.abs(sample.stage.width/sample.stage.height-16/9)<.03,`${label} Camp stage lost its authored 16:9 aspect`);
  const required=['campOptionsBtn','campTalentBtn','campMoonBtn','campInfoBtn','campClassBtn','campPetBtn','campChestBtn','campAchievementBtn','campGoBtn'];
  for(const id of required){const object=sample.objects[id],rect=object?.rect;assert.equal(object?.present,true,`${label} ${id} is missing`);assert.equal(object?.visible,true,`${label} ${id} is not visible`);assert.equal(object?.position,'absolute',`${label} ${id} is no longer a stage object`);assert.equal(object?.inlineTranslate,'none',`${label} ${id} retained a historical translation patch`);assert.ok(rect.left>=-1&&rect.top>=-1&&rect.left+rect.width<=sample.width+1&&rect.top+rect.height<=sample.height+1,`${label} ${id} left the viewport: ${JSON.stringify(rect)}`);}
  const protectedAnchors={
    'wide-desktop':{campOptionsBtn:[.085,.105],campTalentBtn:[.315,.125],campMoonBtn:[.425,.115],campClassBtn:[.225,.405]},
    'compact-desktop':{campOptionsBtn:[.085,.105],campTalentBtn:[.315,.125],campMoonBtn:[.425,.115],campClassBtn:[.225,.405]},
    'stacked-or-short':{campOptionsBtn:[.085,.16],campTalentBtn:[.315,.18],campMoonBtn:[.425,.24],campClassBtn:[.225,.58]}
  }[layout];
  assert.ok(protectedAnchors,`${label} Camp is missing an authoritative anchor contract for ${layout}`);
  for(const [id,[x,y]] of Object.entries(protectedAnchors)){const rect=sample.objects[id].rect,centerX=rect.left+rect.width/2,centerY=rect.top+rect.height/2,expectedX=sample.stage.left+sample.stage.width*x,expectedY=sample.stage.top+sample.stage.height*y;assert.ok(Math.abs(centerX-expectedX)<=3&&Math.abs(centerY-expectedY)<=3,`${label} ${id} drifted from its approved stage anchor`);}
}
function assertClassChooserViewport(sample,label){
  assert.equal(sample.ready,true,`${label} Class chooser did not render`);assert.equal(sample.panelActive,true,`${label} Class chooser did not remain open during viewport resize`);assert.ok(sample.maxScroll>0,`${label} Class chooser roster did not provide a real large-roster scroll range`);assert.equal(sample.donePosition,'sticky',`${label} Class chooser Done lost its sticky chrome treatment`);assert.equal(sample.doneVisible,true,`${label} Class chooser Done left the visible viewport`);assert.equal(sample.positions[0].scrollTop,0,`${label} roster did not reach the top`);assert.ok(sample.positions[1].scrollTop>0,`${label} roster did not reach its middle`);assert.equal(sample.positions[2].scrollTop,sample.maxScroll,`${label} roster did not reach the bottom`);assert.ok(sample.positions.every(position=>position.visible),`${label} Done left the visible viewport while roster scrolled`);assert.match(sample.detailArt||'',/assets\/characters\/classes\/battle\/fighter\.png$/,`${label} Class detail lost semantic battle art during resize`);
}
function assertPetChooserViewport(sample,label){
  assert.equal(sample.ready,true,`${label} Pet chooser did not render`);assert.equal(sample.open,true,`${label} Pet chooser did not remain open during viewport resize`);assert.ok(sample.cards>=13,`${label} Pet chooser did not render the complete unlocked roster`);assert.ok(sample.maxScroll>0,`${label} Pet chooser did not provide a real roster scroll range`);assert.equal(sample.headerPosition,'sticky',`${label} Pet Done header lost its persistent chrome treatment`);assert.equal(sample.doneVisible,true,`${label} Pet Done left the visible viewport`);assert.equal(sample.positions[0].scrollTop,0,`${label} Pet chooser did not reach the top`);assert.ok(sample.positions[1].scrollTop>0,`${label} Pet chooser did not reach its middle`);assert.equal(sample.positions[2].scrollTop,sample.maxScroll,`${label} Pet chooser did not reach the bottom`);assert.ok(sample.positions.every(position=>position.visible),`${label} Pet Done left the visible viewport while roster scrolled`);
}
function assertTalentTreeViewport(sample,label){
  assert.equal(sample.ready,true,`${label} Talent tree did not render`);assert.equal(sample.open,true,`${label} Talent tree did not remain open during viewport resize`);assert.ok(sample.nodes>=40,`${label} Talent tree lost its node roster`);assert.ok(sample.maxScroll>0,`${label} Talent tree lost its pan/scroll range`);assert.equal(sample.doneVisible,true,`${label} Talent Done left the viewport`);assert.equal(sample.headerOutsideScroller,true,`${label} Talent Done became ordinary scroll content`);assert.equal(sample.positions[0].scrollTop,0,`${label} Talent tree did not reach the top`);assert.ok(sample.positions[1].scrollTop>0,`${label} Talent tree did not reach its middle`);assert.equal(sample.positions[2].scrollTop,sample.maxScroll,`${label} Talent tree did not reach the bottom`);assert.ok(sample.positions.every(position=>position.visible),`${label} Talent Done left the viewport while panning`);assert.notEqual(sample.afterWheel,sample.beforeWheel,`${label} mouse-wheel zoom did not change the constellation scale`);assert.equal(sample.minZoom,'28%',`${label} Talent tree lost its overview zoom floor`);assert.equal(sample.maxZoom,'230%',`${label} Talent tree lost its close-inspection zoom ceiling`);
}
function assertPrestigeMoonViewport(sample,label){
  assert.equal(sample.ready,true,`${label} Prestige Moon did not render`);assert.equal(sample.open,true,`${label} Prestige Moon did not remain open during resize`);assert.equal(sample.owner.owner,'ui/prestige-moon',`${label} Prestige Moon lost its presentation owner`);assert.equal(sample.backPosition,'absolute',`${label} Prestige Back lost viewport chrome positioning`);assert.equal(sample.backVisible,true,`${label} Prestige Back left the visible viewport`);assert.match(sample.heldText,/Unspent Prestige Points/,`${label} Prestige held counter disappeared`);assert.equal(sample.tooltipVisible,true,`${label} Prestige held-bonus tooltip did not open from focus`);assert.match(sample.actionText,/Prestige for/,`${label} Prestige reset action disappeared`);assert.equal(sample.nodeCount,2,`${label} Prestige Moon node registry drifted`);assert.equal(sample.hasTopNode,true,`${label} Prestige Moon lost the top purchase node`);assert.match(sample.forgeText,/Cost TBD|awaiting balance approval/,`${label} Forge cost was invented or its TBD state disappeared`);assert.equal(sample.nodesInViewport,true,`${label} a required Prestige node left the viewport`);
}

(async()=>{
  assert.ok(fs.existsSync(EDGE),`Microsoft Edge was not found at ${EDGE}`);
  const profile=fs.mkdtempSync(path.join(os.tmpdir(),"dicebound-run-resume-edge-"));
  const {server,url}=await serveRuntime();let first=null,second=null;
  try{
    first=await launch(profile,url);console.log("Edge pass 1 loaded; checking fresh Camp then writing deterministic checkpoint");
    const freshCamp=await first.evaluate(`(()=>{const ids=['campAchievementBtn','campTalentBtn','campMoonBtn'];return {objects:window.DiceboundCampProgressionTest?.campObjectIds?.()||null,absent:ids.every(id=>!document.getElementById(id))};})()`);
    assert.deepEqual(freshCamp.objects,[],"a fresh career must not render Camp progression objects");assert.equal(freshCamp.absent,true,"fresh Camp objects must be absent rather than invisible controls");
    const manaEquipment=await first.evaluate(`window.DiceboundManaEquipmentTest.exercise()`);
    assert.equal(manaEquipment.one.maxMana,manaEquipment.base.maxMana+5,"Edge authored +Mana gear did not raise the effective cap exactly once");assert.equal(manaEquipment.one.mana,17,"Edge +Mana equipment refilled current Mana");assert.equal(manaEquipment.multiple.maxMana,manaEquipment.base.maxMana+12,"Edge multiple +Mana gear did not aggregate");assert.equal(manaEquipment.multiple.mana,17,"Edge multiple +Mana gear refilled current Mana");assert.deepEqual(manaEquipment.restored,manaEquipment.multiple,"Edge active-run restore changed the effective Mana cap");assert.deepEqual(manaEquipment.removedOne,{maxMana:manaEquipment.base.maxMana+7,mana:17},"Edge replacing one +Mana item did not remove its bonus safely");assert.deepEqual(manaEquipment.removedAll,{maxMana:manaEquipment.base.maxMana,mana:manaEquipment.base.maxMana},"Edge removing the final +Mana item did not clamp current Mana");assert.deepEqual(manaEquipment.nonMana,{maxMana:0,mana:0},"Edge non-Mana class gained a hidden Mana resource from gear");console.log('Edge Mana equipment PASS: effective cap, no-refill, aggregation, checkpoint restore and non-Mana handling agree');
    const birthright=await first.evaluate(`window.DiceboundPrismaticBirthrightTest.exercise()`);
    assert.deepEqual({provenance:birthright.starter.provenance,heirloomEligible:birthright.starter.heirloomEligible,eligible:birthright.starter.eligible},{provenance:'prismatic-birthright',heirloomEligible:false,eligible:false},"Edge Prismatic Birthright did not carry semantic run-only eligibility");assert.equal(birthright.starter.rarity,'common',"Edge Birthright rank 1 rarity changed");assert.ok(birthright.starter.element,"Edge Birthright lost its existing element roll");assert.deepEqual(birthright.endStarterCandidates,[],"Edge end-run heirloom screen offered the Birthright starter");assert.deepEqual(birthright.prestigeStarterCandidates,[],"Edge Prestige heirloom screen offered the Birthright starter");assert.equal(birthright.replacement.eligible,true,"Edge ordinary replacement gear lost normal heirloom eligibility");assert.equal(birthright.replacement.endCandidate,true,"Edge end-run heirloom screen hid an ordinary replacement weapon");assert.deepEqual(birthright.existingHeirloom,{id:'db06422-existing-heirloom',provenance:null,starterGenerated:false},"Edge existing heirloom no longer suppresses Birthright generation");console.log('Edge Prismatic Birthright PASS: semantic run-only starter, heirloom screens and ordinary replacement behavior agree');
    const memoryCamp=await first.evaluate(`(()=>{const api=window.DiceboundMemoryDiagnostics;api.clear();const sample=api.snapshot('edge:fresh-camp');const log=api.formatLog('edge-export-fixture');return {sample,runtimeVersion:window.DiceboundVersion.version,diagnostics:api.diagnostics(),log,controls:['memoryDiagnosticsSnapshot','memoryDiagnosticsRecord','memoryDiagnosticsExport','memoryDiagnosticsClear'].every(id=>!!document.getElementById(id))};})()`);
    assert.equal(memoryCamp.controls,true,"Memory Diagnostics Debug controls are missing");assert.equal(memoryCamp.sample.identity.version,memoryCamp.runtimeVersion);assert.match(memoryCamp.log,/^DiceBound Memory Diagnostics\nGenerated: edge-export-fixture\nVersion: /,"Memory Diagnostics export text is incomplete");assert.ok(memoryCamp.log.includes('edge:fresh-camp'),"Memory Diagnostics export omitted the visible sample line");assert.equal(memoryCamp.sample.state.screen,"Camp");assert.ok(memoryCamp.sample.dom.nodeCount>0,"Memory Diagnostics did not count the live DOM");assert.equal(memoryCamp.sample.timers.available,false,"untracked timers must remain unavailable instead of fabricated");assert.equal(memoryCamp.sample.nativeProcess.available,false,"browser diagnostics must not fabricate native process memory");console.log(`Edge Memory Diagnostics Camp baseline: heap=${memoryCamp.sample.heap.usedBytes===null?'unavailable':memoryCamp.sample.heap.usedBytes} DOM=${memoryCamp.sample.dom.nodeCount}`);
    const memoryStress=await first.evaluate(`window.DiceboundMemoryDiagnosticsStressTest.run(${MEMORY_STRESS_CYCLES})`);
    assert.equal(memoryStress.cycles,MEMORY_STRESS_CYCLES);assert.equal(memoryStress.samples.length,1+MEMORY_STRESS_CYCLES*4,"Edge stress sequence must record Camp -> Board -> Combat -> Board -> Camp for every cycle");assert.equal(memoryStress.equivalent.camp.sampleCount,MEMORY_STRESS_CYCLES+1);assert.equal(memoryStress.equivalent.board.sampleCount,MEMORY_STRESS_CYCLES*2);assert.equal(memoryStress.equivalent.combat.sampleCount,MEMORY_STRESS_CYCLES);assert.ok(memoryStress.equivalent.camp.samples.every(sample=>Number.isInteger(sample.domNodeCount)&&sample.domNodeCount>0),"Edge stress Camp checkpoints need real DOM counts");console.log(`Edge Memory Diagnostics equivalent Camp deltas (${MEMORY_STRESS_CYCLES} cycles): DOM ${memoryStress.equivalent.camp.domNodeDeltas.join(', ')}; heap bytes ${memoryStress.equivalent.camp.heapUsedByteDeltas.join(', ')}`);
    await first.evaluate(`new Promise(resolve=>setTimeout(()=>requestAnimationFrame(()=>requestAnimationFrame(resolve)),180))`);
    const friendsUi=await first.evaluate(`(()=>{const groups=window.DiceboundAchievementHierarchyTest.render(),camp=window.DiceboundCampHitTargetTest.inspect();return {groups,camp,classCount:Object.keys(window.DiceboundContent.classes).length};})()`);
    assert.deepEqual(friendsUi.groups.map(group=>group.id),['top:roads','top:builds','top:legacy','top:secrets','top:hero-mastery']);assert.equal(friendsUi.groups.at(-1).subgroups,friendsUi.classCount,"Hero Mastery must reserve one subgroup per playable class without revealing secrets");assert.ok(friendsUi.camp.filter(item=>item.present).every(item=>item.semantic&&item.focusable),"a visible Camp interaction lost its semantic button/focus target");assert.ok(friendsUi.camp.filter(item=>item.present&&item.painted).every(item=>item.button.width<=item.painted.width+3&&item.button.height<=item.painted.height+3),`Camp has a detached visual hit target: ${JSON.stringify(friendsUi.camp)}`);
    const classChooser=await first.evaluate(`(()=>{const api=window.DiceboundClassChooser,classButton=document.getElementById('campClassBtn'),panel=document.getElementById('campClassPanel');if(!api||!classButton||!panel)return {available:false};classButton.click();const panelOpened=panel.classList.contains('active'),initial=api.inspect(),locked=document.querySelector('.class-choice-card.locked'),lockedId=locked?.dataset.classChoice||null;locked?.click();const lockedInspection=api.inspect(),forced=window.DiceboundV27Test.forceFiveClasses(),afterUnlocks=api.inspect(),randomSelected=api.selectClass('random'),random=api.inspect(),fighterSelected=api.selectClass('fighter'),fighter=api.inspect(),detailArt=document.querySelector('.class-detail-art img')?.getAttribute('src')||null,done=document.querySelector('[data-class-chooser-done]'),sticky=done?getComputedStyle(done).position:null;done?.click();return {available:true,panelOpened,initial,lockedId,lockedInspection,forced,afterUnlocks,randomSelected,random,fighterSelected,fighter,detailArt,sticky,closed:!panel.classList.contains('active')};})()`);
    assert.equal(classChooser.available,true,"Class chooser owner or Camp entrypoint is missing");assert.equal(classChooser.panelOpened,true,"Camp Class must open the chooser destination");assert.equal(classChooser.initial.owner,'ui/class-chooser');assert.ok(classChooser.initial.cards>0,"Class chooser did not render a roster");assert.ok(classChooser.lockedId,"fresh Class chooser did not expose an inspectable locked non-secret class");assert.equal(classChooser.lockedInspection.detail,classChooser.lockedId,"locked class inspection did not preserve a selected detail entry");assert.equal(classChooser.forced.count,1,"Random roster identity must appear once at five unlocked classes");assert.equal(classChooser.afterUnlocks.randomCard,true);assert.equal(classChooser.randomSelected,true);assert.equal(classChooser.random.randomMode,true);assert.equal(classChooser.fighterSelected,true);assert.equal(classChooser.fighter.randomMode,false);assert.equal(classChooser.fighter.selectedClassId,'fighter');assert.match(classChooser.detailArt||'',/assets\/characters\/classes\/battle\/fighter\.png$/,"Class detail must use canonical semantic battle art");assert.equal(classChooser.sticky,'sticky',"Class chooser Done must remain sticky panel chrome");assert.equal(classChooser.closed,true,"Class chooser Done did not return to Camp");console.log('Edge Class chooser PASS: modern roster/detail, locked inspection, Random, semantic art and persistent Done chrome agree');
    await first.evaluate(`document.getElementById('classUnlockRevealOverlay')?.classList.add('hidden')`);
    const chooserWide=await captureClassChooserViewport(first,1360,800);assertClassChooserViewport(chooserWide,'wide Edge');
    const chooserShortWide=await captureClassChooserViewport(first,1200,540);assertClassChooserViewport(chooserShortWide,'short/wide Edge');assert.equal(chooserShortWide.headerDetail,'none','short/wide Edge Class chooser did not compact its descriptive header');
    const chooserCompact=await captureClassChooserViewport(first,960,700);assertClassChooserViewport(chooserCompact,'compact Edge');await first.evaluate(`document.querySelector('[data-class-chooser-done]')?.click()`);assert.equal(await first.evaluate(`document.getElementById('campClassPanel')?.classList.contains('active')||false`),false,'compact Edge Class chooser Done did not return to Camp');await first.send('Emulation.clearDeviceMetricsOverride');console.log('Edge Class chooser viewport PASS: wide, short/wide, compact, resize-open and top/middle/bottom roster scrolling agree');
    const petChooser=await first.evaluate(`(()=>{const api=window.DiceboundPetChooser,campPet=document.getElementById('campPetBtn');if(!api||!campPet)return {available:false};campPet.click();const initial=api.inspect(),locked=document.querySelector('.pet-chooser-card.locked'),lockedId=locked?.dataset.petChoice||null,lockedDisabled=!!locked?.disabled,done=document.querySelector('[data-pet-chooser-done]'),header=document.querySelector('.pet-chooser-chrome');done?.click();document.querySelector('[data-debug="unlockpets"]')?.click();campPet.click();const before=api.inspect(),choice=[...document.querySelectorAll('.pet-chooser-card')].find(button=>!button.disabled&&button.dataset.petChoice!==before.activePet);choice?.click();const selected=api.inspect(),active=document.querySelector('.pet-chooser-card.active')?.dataset.petChoice||null;document.querySelector('[data-pet-chooser-done]')?.click();return {available:true,initial,lockedId,lockedDisabled,before,selected,active,headerPosition:header?getComputedStyle(header).position:null,closed:document.getElementById('petCollectionOverlay')?.classList.contains('hidden'),oldPanel:!!document.getElementById('campPetPanel')};})()`);
    assert.equal(petChooser.available,true,"Pet chooser owner or Camp entrypoint is missing");assert.equal(petChooser.initial.owner,'ui/pet-chooser');assert.ok(petChooser.initial.cards>0,"Pet chooser did not render a roster");assert.ok(petChooser.lockedId,"fresh Pet chooser did not expose a locked companion");assert.equal(petChooser.lockedDisabled,true,"locked Pet chooser entry was selectable");assert.ok(petChooser.before.cards>=13,"debug-unlocked Pet chooser did not scale to the full roster");assert.notEqual(petChooser.selected.activePet,petChooser.initial.activePet,"Pet chooser selection did not reach the authoritative active companion state");assert.equal(petChooser.active,petChooser.selected.activePet,"Pet chooser active card drifted from active Pet state");assert.equal(petChooser.headerPosition,'sticky',"Pet chooser Done must remain viewport/panel chrome");assert.equal(petChooser.closed,true,"Pet chooser Done did not return to Camp");assert.equal(petChooser.oldPanel,false,"retired Camp-only Pet chooser remains live");console.log('Edge Pet chooser PASS: locked/current state, selection, semantic roster and persistent Done chrome agree');
    const petWide=await capturePetChooserViewport(first,1360,800);assertPetChooserViewport(petWide,'wide Edge');
    const petShortWide=await capturePetChooserViewport(first,1200,540);assertPetChooserViewport(petShortWide,'short/wide Edge');
    const petCompact=await capturePetChooserViewport(first,620,700);assertPetChooserViewport(petCompact,'compact Edge');await first.evaluate(`document.querySelector('[data-pet-chooser-done]')?.click()`);assert.equal(await first.evaluate(`document.getElementById('petCollectionOverlay')?.classList.contains('hidden')||false`),true,'compact Edge Pet chooser Done did not return to Camp');await first.send('Emulation.clearDeviceMetricsOverride');console.log('Edge Pet chooser viewport PASS: wide, short/wide, compact, resize-open and top/middle/bottom roster scrolling agree');
    const talentPurchase=await first.evaluate(`(()=>{const api=window.DiceboundTalentTree,debug=document.querySelector('[data-debug="talents"]');debug?.click();api?.open();const node=document.querySelector('[data-talent-id="roadborn"]'),before=node?.textContent||'',locked=!!document.querySelector('.talent-tree-node.locked');node?.click();return new Promise(resolve=>setTimeout(()=>resolve({available:!!api,owner:api?.inspect?.().owner||null,before,after:document.querySelector('[data-talent-id="roadborn"]')?.textContent||'',locked}),35));})()`);
    assert.equal(talentPurchase.available,true,'Talent tree owner is unavailable in Edge');assert.equal(talentPurchase.owner,'ui/talent-tree');assert.equal(talentPurchase.locked,true,'Talent tree lost its locked prerequisite presentation');assert.notEqual(talentPurchase.after,talentPurchase.before,'Talent purchase did not refresh the authoritative node state');
    const talentWide=await captureTalentTreeViewport(first,1360,800);assertTalentTreeViewport(talentWide,'wide Edge');
    const talentShortWide=await captureTalentTreeViewport(first,1200,540);assertTalentTreeViewport(talentShortWide,'short/wide Edge');
    const talentCompact=await captureTalentTreeViewport(first,620,700);assertTalentTreeViewport(talentCompact,'compact Edge');await first.evaluate(`document.querySelector('[data-talent-done]')?.click()`);assert.equal(await first.evaluate(`document.getElementById('talentOverlay')?.classList.contains('hidden')||false`),true,'compact Edge Talent Done did not return to Camp');await first.send('Emulation.clearDeviceMetricsOverride');console.log('Edge Talent tree PASS: purchase, locked state, wide/short-wide/compact pan, wheel zoom and persistent Done chrome agree');
    const prestigeWide=await capturePrestigeMoonViewport(first,1360,800);assertPrestigeMoonViewport(prestigeWide,'wide Edge');
    const prestigeShortWide=await capturePrestigeMoonViewport(first,1200,540);assertPrestigeMoonViewport(prestigeShortWide,'short/wide Edge');
    const prestigeCompact=await capturePrestigeMoonViewport(first,620,700);assertPrestigeMoonViewport(prestigeCompact,'compact Edge');await first.evaluate(`document.querySelector('[data-prestige-back]')?.click()`);assert.equal(await first.evaluate(`document.getElementById('prestigeMoonOverlay')?.classList.contains('hidden')||false`),true,'compact Edge Prestige Back did not return to Camp');await first.send('Emulation.clearDeviceMetricsOverride');console.log('Edge Prestige Moon PASS: scene, held-stat tooltip, data-driven nodes, Forge TBD and persistent Back chrome agree');
    await first.evaluate(`(()=>{document.querySelector('[data-debug="legacy"]')?.click();document.querySelector('[data-debug="talents"]')?.click();return new Promise(resolve=>setTimeout(resolve,80));})()`);
    const campWide=await captureCampViewport(first,1360,800);assertCampViewport(campWide,'wide Edge Camp','wide-desktop');
    const campShortWide=await captureCampViewport(first,1200,540);assertCampViewport(campShortWide,'short/wide Edge Camp','stacked-or-short');
    const campCompact=await captureCampViewport(first,1120,760);assertCampViewport(campCompact,'compact Edge Camp','compact-desktop');await first.send('Emulation.clearDeviceMetricsOverride');console.log('Edge Camp layout PASS: wide, compact and short/wide views retain the approved stage anchors without legacy translations');
    const combatBackgrounds=await first.evaluate(`(()=>{const normal=[1,2,3,4,5,6].map(board=>window.DiceboundCombatBackgrounds?.resolve(board,'normal')?.image||null),nightmare=window.DiceboundCombatBackgrounds?.resolve(3,'nightmare')||null,active=window.DiceboundCombatBackgrounds?.active()?.image||null,overlay=document.getElementById('combatOverlay');return {normal,nightmare,active,attribute:overlay?.dataset.combatBackground||null,style:overlay?.style.getPropertyValue('--db0635-combat-background-image')||null};})()`);
    assert.deepEqual(combatBackgrounds.normal,[1,2,3,4,5,6].map(board=>`assets/combat/backgrounds/board-${board}-normal.png`));assert.equal(combatBackgrounds.nightmare,null,"Nightmare must not use an invented Normal background");assert.equal(combatBackgrounds.active,'assets/combat/backgrounds/board-1-normal.png');assert.equal(combatBackgrounds.attribute,'board-1-normal');assert.match(combatBackgrounds.style,/board-1-normal\.png/);
    const guardians=await first.evaluate(`window.DiceboundGuardianIdentityTest.matrix()`);
    const expectedGuardians=[[1,'normal',false,'ancient-road-dragon','Ancient Road Dragon','Worldfire Breath','ice'],[3,'nightmare',true,'nullstar-hydra','Nullstar Hydra','Erasure of All Roads','light'],[6,'hell',false,'last-equation','The Last Equation','Proof of Extinction','gun']];
    assert.deepEqual(guardians.map(entry=>[entry.board,entry.mode,entry.resumed,entry.id,entry.name,entry.specialName,entry.weakness]),expectedGuardians,"Edge final guardian identity drifted across Board/mode/resume");
    for(const guardian of guardians){assert.equal(guardian.art,`assets/enemies/bosses/battle/${guardian.id}.png`,`Edge ${guardian.id} used a non-canonical battle-art path`);assert.match(guardian.hud,new RegExp(guardian.name.replace(/[.*+?^${}()|[\\]\\]/g,'\\$&')),"Edge guardian HUD drifted from combat identity");}
    console.log('Edge Guardian identity PASS: Boards 1/3/6, Normal/Nightmare/Hell, resume and semantic battle art agree');
    const created=await first.evaluate(`(async()=>{
      document.getElementById('classUnlockRevealOverlay')?.classList.add('hidden');window.DiceboundRng.seed('edge-resume-seed');document.getElementById('campGoBtn').click();
      await new Promise(resolve=>setTimeout(resolve,240));document.getElementById('classUnlockRevealOverlay')?.classList.add('hidden');
      const automaticSaved=!!window.DiceboundRunCheckpoint.load().checkpoint;
      const checkpoint=window.DiceboundRunResumeTest.snapshot();checkpoint.run.player.gold=321;checkpoint.run.player.position=Math.min(2,checkpoint.run.tiles.length-1);checkpoint.summary.gold=321;checkpoint.summary.tile=checkpoint.run.player.position+1;
      window.DiceboundRunCheckpoint.store(checkpoint);const expected=[window.DiceboundRng.random(),window.DiceboundRng.random(),window.DiceboundRng.random()];
      const markerSources=[...document.querySelectorAll('.tile.enemy img.db-road-marker')].map(image=>image.getAttribute('src'));
      return {title:document.title,expectedTitle:'Dicebound: '+window.DiceboundVersion.channel+' v'+window.DiceboundVersion.version,checkpoint,expected,stable:window.DiceboundRunResumeTest.isStable(),automaticSaved,markerSources};
    })()`);
    assert.equal(created.title,created.expectedTitle);assert.equal(created.stable,true);assert.equal(created.automaticSaved,true,"starting a stable run did not autosave");assert.equal(created.checkpoint.run.player.gold,321);
    const memoryRun=await first.evaluate(`(async()=>{const api=window.DiceboundMemoryDiagnostics;api.setRecording(true);const overlay=document.getElementById('infoOverlay');overlay.classList.remove('hidden');await new Promise(resolve=>setTimeout(resolve,35));overlay.classList.add('hidden');await new Promise(resolve=>setTimeout(resolve,35));const sample=api.snapshot('edge:board');const samples=api.samples();api.setRecording(false);return {sample,reasons:samples.map(entry=>entry.reason),screens:samples.map(entry=>entry.state.screen),activeOverlays:[...document.querySelectorAll('.overlay:not(.hidden)')].map(node=>node.id),diagnostics:api.diagnostics()};})()`);
    assert.equal(memoryRun.sample.state.screen,"Board",`an overlay remained open after the Pet chooser checks: ${JSON.stringify(memoryRun.activeOverlays)}`);assert.ok(memoryRun.reasons.includes('recording-enabled'),"recording did not create its initial bounded sample");assert.ok(memoryRun.screens.includes('Modal'),"recording did not capture a major overlay lifecycle state");assert.equal(memoryRun.diagnostics.recording,false,"recording toggle did not stop its sampler");console.log(`Edge Memory Diagnostics Board baseline: heap=${memoryRun.sample.heap.usedBytes===null?'unavailable':memoryRun.sample.heap.usedBytes} DOM=${memoryRun.sample.dom.nodeCount} samples=${memoryRun.reasons.length}`);
    const merchantTransaction=await first.evaluate(`(async()=>{const api=window.DiceboundMerchantTransactionTest,prepared=api.prepareSovereign();document.querySelector('#shopGrid button').click();await new Promise(resolve=>setTimeout(resolve,30));const pending=api.state(),delayed=api.attemptDelayedReopen(),afterDelayed=api.state(),choice=document.querySelector('#sovereignChoiceGrid button');if(!choice)throw new Error('Sovereign choice did not render an eligible Legendary');choice.click();await new Promise(resolve=>setTimeout(resolve,30));return {prepared,pending,delayed,afterDelayed,settled:api.state()};})()`);
    assert.equal(merchantTransaction.pending.visit.activeChoice!==null,true,"Edge Sovereign choice did not own the Merchant transaction");assert.equal(merchantTransaction.pending.items[0].sold,true,"Edge Sovereign offer was not consumed before selection");assert.equal(merchantTransaction.delayed.result,false,"Edge delayed Merchant reopen was not rejected during a choice");assert.equal(merchantTransaction.delayed.sameStock,true,"Edge delayed Merchant reopen rebuilt stock during a choice");assert.equal(merchantTransaction.afterDelayed.visit.activeChoice!==null,true,"Edge delayed Merchant reopen cleared the active choice");assert.equal(merchantTransaction.settled.visit.activeChoice,null,"Edge Sovereign choice did not settle");assert.equal(merchantTransaction.settled.items[0].sold,true,"Edge Sovereign offer became purchasable again after selection");console.log('Edge Merchant transaction PASS: delayed Sovereign selection keeps stock frozen and consumed');
    const vines=await first.evaluate(`(async()=>{const api=window.DiceboundNatureVfxTest,effect=api.effect(),load=src=>new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve({width:image.naturalWidth,height:image.naturalHeight});image.onerror=()=>reject(new Error('Could not load '+src));image.src=src;}),frames=await Promise.all(effect.frames.map(load)),targets=api.livingTargets([{name:'defeated',hp:0},{name:'living',hp:4},{name:'missing'}]),preview=api.previewPlayer();await new Promise(resolve=>setTimeout(resolve,110));const active=api.active();await new Promise(resolve=>setTimeout(resolve,820));return {frames,targets,preview,active,after:api.active(),style:!!document.getElementById('dicebound-nature-vfx-style')};})()`);
    assert.equal(vines.style,true,"Nature VFX stylesheet is missing");assert.equal(vines.preview,true);assert.deepEqual(vines.targets,['living']);assert.equal(vines.frames.length,8);for(const frame of vines.frames)assert.deepEqual(frame,{width:272,height:724});assert.equal(vines.active.length,1);assert.equal(vines.active[0].target,'player');assert.deepEqual(vines.after,[]);
    const donuts=await first.evaluate(`(async()=>{window.DiceboundNatureVfxTest.exerciseProc('nature');const api=window.DiceboundDonutVfxTest,effect=api.effect(),playerPlayed=api.play({origin:'player'});await new Promise(resolve=>setTimeout(resolve,120));const playerActive=api.active();const enemyPlayed=api.play({origin:'enemy'});await new Promise(resolve=>setTimeout(resolve,120));const enemyActive=api.active();await new Promise(resolve=>setTimeout(resolve,1600));return {effect,playerPlayed,playerActive,enemyPlayed,enemyActive,after:api.active(),style:!!document.getElementById('dicebound-donut-vfx-style')};})()`);
    const expectedDonutTargets=origin=>[{src:'assets/combat/effects/donut/donut-proc-rain-spritesheet.png',effect:'donutProcRain',target:'player',origin,frame:0},{src:'assets/combat/effects/donut/donut-proc-rain-spritesheet.png',effect:'donutProcRain',target:'enemy',origin,frame:0}];assert.equal(donuts.effect.image,'assets/combat/effects/donut/donut-proc-rain-spritesheet.png');assert.deepEqual([donuts.effect.frameCount,donuts.effect.frameWidth,donuts.effect.frameHeight],[6,362,724]);assert.equal(donuts.style,true,"Donut VFX stylesheet is missing");assert.equal(donuts.playerPlayed,true,"player-origin Donut VFX did not attach to player and selected-target hosts");assert.deepEqual(donuts.playerActive,expectedDonutTargets('player'));assert.equal(donuts.enemyPlayed,true,"enemy-origin Donut VFX did not attach to player and selected-target hosts");assert.deepEqual(donuts.enemyActive,expectedDonutTargets('enemy'));assert.deepEqual(donuts.after,[],"Donut VFX did not clean up after its authored duration");
    const natureProc=await first.evaluate(`(async()=>{const api=window.DiceboundNatureVfxTest,nature=api.exerciseProc('nature');await new Promise(resolve=>setTimeout(resolve,110));const active=api.active();const ordinary=api.exerciseProc('fire');return {nature,active,ordinary,afterOrdinary:api.active()};})()`);
    assert.equal(natureProc.nature.activated,true,"forced Nature proc did not activate");assert.deepEqual(natureProc.nature.enemies.map(enemy=>enemy.hp),[0,8,8]);assert.deepEqual(natureProc.nature.enemies.map(enemy=>enemy.poisonStacks),[0,1,1]);assert.deepEqual(natureProc.active.map(effect=>effect.enemyIndex),[1,2],"Nature VFX must follow living targets actually affected by the pack proc");assert.ok(natureProc.active.every(effect=>effect.target==='enemy'));assert.equal(natureProc.nature.legacyPresentation.nature,0,"authored Nature vines must replace the legacy generic Nature effect");
    assert.equal(natureProc.ordinary.activated,true,"ordinary forced proc did not activate");assert.deepEqual(natureProc.afterOrdinary,[],"ordinary non-Nature proc created a Nature VFX overlay");assert.ok(natureProc.ordinary.legacyPresentation.fire>0,"ordinary Fire proc lost its generic elemental presentation");assert.equal(natureProc.ordinary.legacyPresentation.nature,0,"Fire proc created a legacy Nature presentation");
    const presentation=await first.evaluate(`(()=>['miniboss','final','slime','wolf'].map(kind=>window.DiceboundNatureVfxTest.exercisePresentation(kind)))()`);
    const byKind=Object.fromEntries(presentation.map(entry=>[entry.kind,entry]));const narrow=byKind.final.narrow,minimumMini=narrow?{width:190,height:200}:{width:250,height:250},minimumFinal=narrow?{width:250,height:265}:{width:320,height:330};assert.match(byKind.miniboss.hostClasses,/miniboss/);assert.match(byKind.final.hostClasses,/final-boss/);assert.ok(byKind.miniboss.art.width>=minimumMini.width&&byKind.miniboss.art.height>=minimumMini.height,`miniboss frame regressed below the approved visual floor: ${JSON.stringify(byKind.miniboss)}`);assert.ok(byKind.final.art.width>=minimumFinal.width&&byKind.final.art.height>=minimumFinal.height,`final-boss frame regressed below the approved visual floor: ${JSON.stringify(byKind.final)}`);assert.ok(byKind.final.art.width>byKind.miniboss.art.width&&byKind.final.art.height>byKind.miniboss.art.height,`final boss must remain more imposing than miniboss: ${JSON.stringify({miniboss:byKind.miniboss,final:byKind.final})}`);assert.ok(byKind.final.art.width>byKind.final.player.width,`final boss portrait must be larger than the player portrait: ${JSON.stringify(byKind.final)}`);assert.match(byKind.slime.stageClasses,/db0636-tiered-enemy-stage/);assert.match(byKind.wolf.stageClasses,/db0636-tiered-enemy-stage/);assert.ok(byKind.slime.sprite.width>0&&byKind.slime.sprite.height>0,`Slime tier art did not render: ${JSON.stringify(byKind.slime)}`);assert.deepEqual(byKind.wolf.sprite,byKind.slime.sprite,"Wolf and Slime tier art must share the ordinary-enemy responsive stage");assert.ok(byKind.slime.sprite.height<byKind.miniboss.art.height,"tiered ordinary-enemy art must remain vertically smaller than guardian art");
    assert.ok(created.markerSources.length>0,"board did not render any semantic ordinary-enemy markers");assert.ok(created.markerSources.every(src=>/assets\/enemies\/normal\/board-markers\/[a-z-]+\.png$/.test(src||'')),"board used a non-semantic ordinary-enemy marker source");
    const tieredArt=await first.evaluate(`(async()=>{const assets=window.DiceboundAssets,battle=window.DiceboundEnemyBattleArt,load=src=>new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve({width:image.naturalWidth,height:image.naturalHeight});image.onerror=()=>reject(new Error('Could not load '+src));image.src=src;});const families=await Promise.all(['slime','wolf'].map(async identity=>({identity,forms:await Promise.all([1,2,3,4,5,6].map(async board=>{const art=battle.resolve(identity==='slime'?'Nightmare Slime':'Ascended Wolf',board),size=await load(art.src);return {board,src:art.src,resolvedBoard:art.board,size};}))})));return {families,modes:['normal','nightmare','hell'].map(mode=>assets.resolveEnemyModeAura(mode)),style:!!document.getElementById('dicebound-0636-slime-battle-art-style')};})()`);
    assert.equal(tieredArt.style,true,"tiered ordinary-enemy battle-art presentation stylesheet is missing");
    for(const family of tieredArt.families){assert.deepEqual(family.forms.map(x=>x.resolvedBoard),[1,2,3,4,5,6]);assert.deepEqual(family.forms.map(x=>x.src),[1,2,3,4,5,6].map(board=>`assets/enemies/normal/battle/${family.identity}-board-${board}.png`));for(const form of family.forms)assert.deepEqual(form.size,{width:1086,height:1448});}
    assert.deepEqual(tieredArt.modes,[{id:'normal',className:''},{id:'nightmare',className:'db-enemy-mode-nightmare'},{id:'hell',className:'db-enemy-mode-hell'}]);
    const chainedTargets=await first.evaluate(`window.DiceboundTargetPresentationTest.chainedKills()`);
    const expectedTargetSteps=[['normal',0,'Target A'],['echo',1,'Target B'],['echo',2,'Target C']];
    assert.deepEqual(chainedTargets.captures.map(step=>[step.mode,step.surfaces.currentIndex,step.surfaces.currentName]),expectedTargetSteps,"Edge chained strikes did not enter each animation with the living mechanical target selected");
    for(const [index,event] of chainedTargets.events.entries()){const nextHp=index+2;assert.equal(event.targetHp,0,"Edge regression fixture must kill each chained target");assert.deepEqual(event.presentationTarget,{index:index+1,name:`Target ${['B','C','D'][index]}`,alive:true},"Edge strike event exposed a stale presentation target");assert.equal(event.surfaces.currentIndex,index+1,"Edge target arrow/glow index lagged behind the resolved target");assert.equal(event.surfaces.stageIndex,index+1,"Edge selected stage host still pointed at a defeated target");assert.equal(event.surfaces.activeChipCount,1,"Edge target selector must have exactly one active living target");assert.match(event.surfaces.enemyName,new RegExp(`Target ${['B','C','D'][index]}`),"Edge target HUD name lagged behind the resolved target");assert.match(event.surfaces.enemyHp,new RegExp(`${nextHp} / ${nextHp}`),"Edge target HP panel lagged behind the resolved target");}
    assert.deepEqual(chainedTargets.living,['Target D']);assert.equal(chainedTargets.afterDelay.stageIndex,3,"Edge target selection regressed during the chained-hit presentation delay");console.log('Edge chained target presentation PASS: HUD, selected host and selector advance before Echoes');
    const passivePoisonTarget=await first.evaluate(`window.DiceboundTargetPresentationTest.passivePoisonDeath()`);
    assert.equal(passivePoisonTarget.dealt,1,"Edge Poison regression fixture did not deal its capped lethal tick");assert.equal(passivePoisonTarget.defeatedHp,0);assert.deepEqual(passivePoisonTarget.living,['Poison Target B']);assert.deepEqual(passivePoisonTarget.events,[{reason:'poison',defeatedIndex:0,targetIndex:1,targetName:'Poison Target B'}]);assert.equal(passivePoisonTarget.surfaces.currentIndex,1,"Edge Poison death did not advance the authoritative selected target");assert.equal(passivePoisonTarget.surfaces.stageIndex,1,"Edge Poison death left its selected stage host on the defeated target");console.log('Edge passive target reconciliation PASS: Poison death advances to the living selected target');
    await closeEdge(first);first=null;console.log("Edge pass 1 closed; relaunching the same profile");

    second=await launch(profile,url);console.log("Edge pass 2 loaded; continuing saved run");
    const camp=await second.evaluate(`({visible:!document.getElementById('runResumePanel').classList.contains('hidden'),enabled:!document.getElementById('runResumeBtn').disabled,summary:document.getElementById('runResumeSummary').textContent})`);
    assert.equal(camp.visible,true);assert.equal(camp.enabled,true);assert.match(camp.summary,/321 gold/);
    const resumed=await second.evaluate(`(async()=>{document.getElementById('runResumeBtn').click();await new Promise(resolve=>setTimeout(resolve,180));const state=window.DiceboundRunResumeTest.state();return {state,next:[window.DiceboundRng.random(),window.DiceboundRng.random(),window.DiceboundRng.random()],startHidden:document.getElementById('startOverlay').classList.contains('hidden')};})()`);
    assert.equal(resumed.state.gameStarted,true);assert.equal(resumed.state.rollLocked,false);assert.equal(resumed.state.player.gold,321);assert.equal(resumed.state.position,created.checkpoint.run.player.position);assert.deepEqual(resumed.next,created.expected);assert.equal(resumed.startHidden,true);
    const transientBlocked=await second.evaluate(`(()=>{document.getElementById('eventOverlay').classList.remove('hidden');const saved=window.DiceboundRunResumeTest.save();document.getElementById('eventOverlay').classList.add('hidden');return saved;})()`);
    assert.equal(transientBlocked,false,"an unsafe overlay allowed a replacement checkpoint");
    console.log(`Edge active-run relaunch PASS: ${camp.summary}; exact RNG cursor and transient-state guard preserved`);
  } finally {
    if(first)await closeEdge(first);if(second)await closeEdge(second);await new Promise(resolve=>server.close(resolve));await removeTempProfile(profile);
  }
})().catch(error=>{console.error(error);process.exitCode=1;});
