"use strict";

const assert=require("node:assert/strict");
const childProcess=require("node:child_process");
const fs=require("node:fs");
const os=require("node:os");
const path=require("node:path");

const ROOT=path.join(__dirname,".."),RELEASE_DIR=path.join(ROOT,"wrapper-source","release"),DEBUG_PORT=Number(process.env.DICEBOUND_NATIVE_DEBUG_PORT||19358);
function newestReleaseExe(){
  if(!fs.existsSync(RELEASE_DIR))return path.join(RELEASE_DIR,"DiceBound.exe");
  return fs.readdirSync(RELEASE_DIR)
    .filter(name=>/^Dicebound_Beta_[\d_]+\.exe$/i.test(name))
    .map(name=>({path:path.join(RELEASE_DIR,name),mtime:fs.statSync(path.join(RELEASE_DIR,name)).mtimeMs}))
    .sort((left,right)=>right.mtime-left.mtime)[0]?.path||path.join(RELEASE_DIR,"DiceBound.exe");
}
const EXE=process.env.DICEBOUND_NATIVE_EXE||newestReleaseExe();
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function waitForTargets(timeout=25000){const deadline=Date.now()+timeout;let last;while(Date.now()<deadline){try{const response=await fetch(`http://127.0.0.1:${DEBUG_PORT}/json/list`);if(response.ok)return response.json();}catch(error){last=error;}await sleep(100);}throw last||new Error("Native WebView2 DevTools endpoint did not start");}
async function connectNative(){
  const deadline=Date.now()+25000;let target=null;
  while(Date.now()<deadline&&!target){const targets=await waitForTargets();target=targets.find(item=>item.type==="page"&&item.webSocketDebuggerUrl&&item.url.includes("diceboundNative=1"));if(!target)await sleep(100);}
  if(!target)throw new Error("Native DiceBound page target was not exposed");
  const socket=new WebSocket(target.webSocketDebuggerUrl),pending=new Map();let id=0;
  await new Promise((resolve,reject)=>{socket.addEventListener("open",resolve,{once:true});socket.addEventListener("error",reject,{once:true});});
  socket.addEventListener("message",event=>{const message=JSON.parse(String(event.data)),request=pending.get(message.id);if(!request)return;pending.delete(message.id);message.error?request.reject(new Error(message.error.message)):request.resolve(message.result);});
  function send(method,params={}){return new Promise((resolve,reject)=>{const requestId=++id;pending.set(requestId,{resolve,reject});socket.send(JSON.stringify({id:requestId,method,params}));});}
  async function evaluate(expression){const result=await send("Runtime.evaluate",{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw new Error(result.exceptionDetails.exception?.description||result.exceptionDetails.text);return result.result.value;}
  return {socket,evaluate};
}
async function launch(localAppData){
  const env={...process.env,LOCALAPPDATA:localAppData,WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS:`--remote-debugging-port=${DEBUG_PORT}`,DICEBOUND_WEBVIEW2_LOADER:""};
  const child=childProcess.spawn(EXE,[],{env,stdio:"ignore",windowsHide:true}),page=await connectNative(),deadline=Date.now()+25000;
  while(Date.now()<deadline){if(await page.evaluate("document.readyState==='complete'&&!!window.DiceboundRunResumeTest"))return {child,...page};await sleep(100);}
  child.kill();throw new Error("Native DiceBound runtime did not complete startup");
}
async function stop(instance){try{instance.socket.close();}catch(_){}if(instance.child.exitCode===null)instance.child.kill();if(instance.child.exitCode===null)await Promise.race([new Promise(resolve=>instance.child.once("exit",resolve)),sleep(5000)]);}

(async()=>{
  assert.ok(fs.existsSync(EXE),`Native DiceBound EXE was not found at ${EXE}`);
  const root=fs.mkdtempSync(path.join(os.tmpdir(),"dicebound-native-resume-")),localAppData=path.join(root,"LocalAppData");fs.mkdirSync(localAppData,{recursive:true});let first=null,second=null;
  try{
    first=await launch(localAppData);console.log("Native pass 1 loaded through WebView2; checking fresh Camp then writing deterministic checkpoint");
    const freshCamp=await first.evaluate(`(()=>{const ids=['campAchievementBtn','campTalentBtn','campMoonBtn'];return {objects:window.DiceboundCampProgressionTest?.campObjectIds?.()||null,absent:ids.every(id=>!document.getElementById(id))};})()`);
    assert.deepEqual(freshCamp.objects,[],"a fresh native career must not render Camp progression objects");assert.equal(freshCamp.absent,true,"fresh native Camp objects must be absent rather than invisible controls");
    const memoryCamp=await first.evaluate(`(()=>{const api=window.DiceboundMemoryDiagnostics;api.clear();const sample=api.snapshot('native:fresh-camp');return {sample,runtimeVersion:window.DiceboundVersion.version,diagnostics:api.diagnostics(),controls:['memoryDiagnosticsSnapshot','memoryDiagnosticsRecord','memoryDiagnosticsClear'].every(id=>!!document.getElementById(id))};})()`);
    assert.equal(memoryCamp.controls,true,"native Memory Diagnostics Debug controls are missing");assert.equal(memoryCamp.sample.identity.version,memoryCamp.runtimeVersion);assert.equal(memoryCamp.sample.state.screen,"Camp");assert.ok(memoryCamp.sample.dom.nodeCount>0,"native Memory Diagnostics did not count the live DOM");assert.equal(memoryCamp.sample.timers.available,false,"native untracked timers must remain unavailable instead of fabricated");assert.equal(memoryCamp.sample.nativeProcess.available,false,"native process memory must remain unavailable without a host API");console.log(`Native Memory Diagnostics Camp baseline: heap=${memoryCamp.sample.heap.usedBytes===null?'unavailable':memoryCamp.sample.heap.usedBytes} DOM=${memoryCamp.sample.dom.nodeCount}`);
    const friendsUi=await first.evaluate(`(()=>{const groups=window.DiceboundAchievementHierarchyTest.render(),camp=window.DiceboundCampHitTargetTest.inspect();return {groups,camp,classCount:Object.keys(window.DiceboundContent.classes).length};})()`);
    assert.deepEqual(friendsUi.groups.map(group=>group.id),['top:roads','top:builds','top:legacy','top:secrets','top:hero-mastery']);assert.equal(friendsUi.groups.at(-1).subgroups,friendsUi.classCount,"native Hero Mastery must reserve one subgroup per playable class without revealing secrets");assert.ok(friendsUi.camp.filter(item=>item.present).every(item=>item.semantic&&item.focusable),"a visible native Camp interaction lost its semantic button/focus target");assert.ok(friendsUi.camp.filter(item=>item.present&&item.painted).every(item=>item.button.width<=item.painted.width+3&&item.button.height<=item.painted.height+3),`native Camp has a detached visual hit target: ${JSON.stringify(friendsUi.camp)}`);
    const combatBackgrounds=await first.evaluate(`(()=>{const normal=[1,2,3,4,5,6].map(board=>window.DiceboundCombatBackgrounds?.resolve(board,'normal')?.image||null),nightmare=window.DiceboundCombatBackgrounds?.resolve(3,'nightmare')||null,active=window.DiceboundCombatBackgrounds?.active()?.image||null,overlay=document.getElementById('combatOverlay');return {normal,nightmare,active,attribute:overlay?.dataset.combatBackground||null,style:overlay?.style.getPropertyValue('--db0635-combat-background-image')||null};})()`);
    assert.deepEqual(combatBackgrounds.normal,[1,2,3,4,5,6].map(board=>`assets/combat/backgrounds/board-${board}-normal.png`));assert.equal(combatBackgrounds.nightmare,null,"native Nightmare must not use an invented Normal background");assert.equal(combatBackgrounds.active,'assets/combat/backgrounds/board-1-normal.png');assert.equal(combatBackgrounds.attribute,'board-1-normal');assert.match(combatBackgrounds.style,/board-1-normal\.png/);
    const created=await first.evaluate(`(async()=>{window.DiceboundRng.seed('native-resume-seed');document.getElementById('campGoBtn').click();await new Promise(resolve=>setTimeout(resolve,240));const automaticSaved=!!window.DiceboundRunCheckpoint.load().checkpoint;const checkpoint=window.DiceboundRunResumeTest.snapshot();checkpoint.run.player.gold=654;checkpoint.run.player.position=Math.min(3,checkpoint.run.tiles.length-1);checkpoint.summary.gold=654;checkpoint.summary.tile=checkpoint.run.player.position+1;window.DiceboundRunCheckpoint.store(checkpoint);const expected=[window.DiceboundRng.random(),window.DiceboundRng.random(),window.DiceboundRng.random()];const version=window.DiceboundVersion.version,channel=window.DiceboundVersion.channel;const markerSources=[...document.querySelectorAll('.tile.enemy img.db-road-marker')].map(image=>image.getAttribute('src'));return {title:document.title,expectedTitle:'Dicebound: '+channel+' v'+version,readyLog:'Frontend ready handshake received for '+channel+' '+version+'.',storage:window.DiceboundStorage.diagnostics(),checkpoint,expected,automaticSaved,markerSources};})()`);
    assert.equal(created.title,created.expectedTitle);assert.equal(created.storage.backend,"wrapper-native");assert.equal(created.automaticSaved,true,"starting a stable native run did not autosave");
    const memoryRun=await first.evaluate(`(async()=>{const api=window.DiceboundMemoryDiagnostics;api.setRecording(true);const overlay=document.getElementById('infoOverlay');overlay.classList.remove('hidden');await new Promise(resolve=>setTimeout(resolve,35));overlay.classList.add('hidden');await new Promise(resolve=>setTimeout(resolve,35));const sample=api.snapshot('native:board');const samples=api.samples();api.setRecording(false);return {sample,reasons:samples.map(entry=>entry.reason),screens:samples.map(entry=>entry.state.screen),diagnostics:api.diagnostics()};})()`);
    assert.equal(memoryRun.sample.state.screen,"Board");assert.ok(memoryRun.reasons.includes('recording-enabled'),"native recording did not create its initial bounded sample");assert.ok(memoryRun.screens.includes('Modal'),"native recording did not capture a major overlay lifecycle state");assert.equal(memoryRun.diagnostics.recording,false,"native recording toggle did not stop its sampler");console.log(`Native Memory Diagnostics Board baseline: heap=${memoryRun.sample.heap.usedBytes===null?'unavailable':memoryRun.sample.heap.usedBytes} DOM=${memoryRun.sample.dom.nodeCount} samples=${memoryRun.reasons.length}`);
    const vines=await first.evaluate(`(async()=>{const api=window.DiceboundNatureVfxTest,effect=api.effect(),load=src=>new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve({width:image.naturalWidth,height:image.naturalHeight});image.onerror=()=>reject(new Error('Could not load '+src));image.src=src;}),frames=await Promise.all(effect.frames.map(load)),targets=api.livingTargets([{name:'defeated',hp:0},{name:'living',hp:4},{name:'missing'}]),preview=api.previewPlayer();await new Promise(resolve=>setTimeout(resolve,110));const active=api.active();await new Promise(resolve=>setTimeout(resolve,620));return {frames,targets,preview,active,after:api.active(),style:!!document.getElementById('dicebound-nature-vfx-style')};})()`);
    assert.equal(vines.style,true,"native Nature VFX stylesheet is missing");assert.equal(vines.preview,true);assert.deepEqual(vines.targets,['living']);assert.equal(vines.frames.length,8);for(const frame of vines.frames)assert.deepEqual(frame,{width:272,height:724});assert.equal(vines.active.length,1);assert.equal(vines.active[0].target,'player');assert.deepEqual(vines.after,[]);
    const donuts=await first.evaluate(`(async()=>{const api=window.DiceboundDonutVfxTest,effect=api.effect(),played=api.play();await new Promise(resolve=>setTimeout(resolve,120));const active=api.active();await new Promise(resolve=>setTimeout(resolve,1600));return {effect,played,active,after:api.active()};})()`);
    assert.equal(donuts.effect.image,'assets/combat/effects/donut-proc-rain-spritesheet.png');assert.equal(donuts.played,true,"native Donut VFX did not attach to the combat presentation host");assert.deepEqual(donuts.active,[{src:'assets/combat/effects/donut-proc-rain-spritesheet.png',effect:'donutProcRain'}]);assert.deepEqual(donuts.after,[],"native Donut VFX did not clean up after its authored duration");
    const natureProc=await first.evaluate(`(async()=>{const api=window.DiceboundNatureVfxTest,nature=api.exerciseProc('nature');await new Promise(resolve=>setTimeout(resolve,110));const active=api.active();const ordinary=api.exerciseProc('fire');return {nature,active,ordinary,afterOrdinary:api.active()};})()`);
    assert.equal(natureProc.nature.activated,true,"forced native Nature proc did not activate");assert.deepEqual(natureProc.nature.enemies.map(enemy=>enemy.hp),[0,8,8]);assert.deepEqual(natureProc.nature.enemies.map(enemy=>enemy.poisonStacks),[0,1,1]);assert.deepEqual(natureProc.active.map(effect=>effect.enemyIndex),[1,2],"native Nature VFX must follow living targets actually affected by the pack proc");assert.ok(natureProc.active.every(effect=>effect.target==='enemy'));assert.equal(natureProc.nature.legacyPresentation.nature,0,"authored native Nature vines must replace the legacy generic Nature effect");
    assert.equal(natureProc.ordinary.activated,true,"ordinary forced native proc did not activate");assert.deepEqual(natureProc.afterOrdinary,[],"ordinary native non-Nature proc created a Nature VFX overlay");assert.ok(natureProc.ordinary.legacyPresentation.fire>0,"ordinary native Fire proc lost its generic elemental presentation");assert.equal(natureProc.ordinary.legacyPresentation.nature,0,"native Fire proc created a legacy Nature presentation");
    const presentation=await first.evaluate(`(()=>['miniboss','final','slime','wolf'].map(kind=>window.DiceboundNatureVfxTest.exercisePresentation(kind)))()`);
    const byKind=Object.fromEntries(presentation.map(entry=>[entry.kind,entry]));const narrow=byKind.final.narrow,miniSize=narrow?96:120,finalSize=narrow?190:270,tieredHeight=narrow?Math.min(202,Math.max(128,Math.round(byKind.slime.viewportHeight*.24))):Math.min(342,Math.max(176,Math.round(byKind.slime.viewportHeight*.27)));assert.match(byKind.miniboss.hostClasses,/miniboss/);assert.match(byKind.final.hostClasses,/final-boss/);assert.deepEqual(byKind.miniboss.art,{width:miniSize,height:miniSize});assert.deepEqual(byKind.final.art,{width:finalSize,height:finalSize});assert.ok(byKind.final.art.width>byKind.final.player.width,`native final boss portrait must be larger than the player portrait: ${JSON.stringify(byKind.final)}`);assert.match(byKind.slime.stageClasses,/db0636-tiered-enemy-stage/);assert.match(byKind.wolf.stageClasses,/db0636-tiered-enemy-stage/);assert.equal(byKind.slime.sprite.height,tieredHeight);assert.equal(byKind.wolf.sprite.height,tieredHeight);
    assert.ok(created.markerSources.length>0,"native board did not render any semantic ordinary-enemy markers");assert.ok(created.markerSources.every(src=>/assets\/enemies\/normal\/board-markers\/[a-z-]+\.png$/.test(src||'')),"native board used a non-semantic ordinary-enemy marker source");
    const tieredArt=await first.evaluate(`(async()=>{const assets=window.DiceboundAssets,battle=window.DiceboundEnemyBattleArt,load=src=>new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve({width:image.naturalWidth,height:image.naturalHeight});image.onerror=()=>reject(new Error('Could not load '+src));image.src=src;});const families=await Promise.all(['slime','wolf'].map(async identity=>({identity,forms:await Promise.all([1,2,3,4,5,6].map(async board=>{const art=battle.resolve(identity==='slime'?'Slime':'Wolf',board),size=await load(art.src);return {board,src:art.src,resolvedBoard:art.board,size};}))})));return {families,modes:['normal','nightmare','hell'].map(mode=>assets.resolveEnemyModeAura(mode)),style:!!document.getElementById('dicebound-0636-slime-battle-art-style')};})()`);
    assert.equal(tieredArt.style,true,"native tiered ordinary-enemy battle-art presentation stylesheet is missing");
    for(const family of tieredArt.families){assert.deepEqual(family.forms.map(x=>x.resolvedBoard),[1,2,3,4,5,6]);assert.deepEqual(family.forms.map(x=>x.src),[1,2,3,4,5,6].map(board=>`assets/enemies/normal/battle/${family.identity}-board-${board}.png`));for(const form of family.forms)assert.deepEqual(form.size,{width:1086,height:1448});}
    assert.deepEqual(tieredArt.modes,[{id:'normal',className:''},{id:'nightmare',className:'db-enemy-mode-nightmare'},{id:'hell',className:'db-enemy-mode-hell'}]);
    await stop(first);first=null;await sleep(800);

    second=await launch(localAppData);console.log("Native pass 2 relaunched the same isolated app-data; continuing saved run");
    const camp=await second.evaluate(`({visible:!document.getElementById('runResumePanel').classList.contains('hidden'),enabled:!document.getElementById('runResumeBtn').disabled,summary:document.getElementById('runResumeSummary').textContent})`);
    assert.equal(camp.visible,true);assert.equal(camp.enabled,true);assert.match(camp.summary,/654 gold/);
    const resumed=await second.evaluate(`(async()=>{document.getElementById('runResumeBtn').click();await new Promise(resolve=>setTimeout(resolve,180));return {state:window.DiceboundRunResumeTest.state(),next:[window.DiceboundRng.random(),window.DiceboundRng.random(),window.DiceboundRng.random()]};})()`);
    assert.equal(resumed.state.gameStarted,true);assert.equal(resumed.state.player.gold,654);assert.equal(resumed.state.position,created.checkpoint.run.player.position);assert.deepEqual(resumed.next,created.expected);
    const log=fs.readFileSync(path.join(localAppData,"Dicebound","logs","native-wrapper.log"),"utf8");assert.match(log,/WebView2 bootstrap mode=official-loader/);assert.ok(log.split(created.readyLog).length-1>=2,"both native launches did not report frontend-ready");
    console.log(`Native WebView2 active-run relaunch PASS: ${camp.summary}; official loader, native storage and exact RNG cursor verified`);
  } finally {if(first)await stop(first);if(second)await stop(second);await sleep(500);fs.rmSync(root,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
