const fs=require("fs");
const vm=require("vm");
const path=require("path");
const root=path.resolve(__dirname,"..");
function load(rel,window={}){const code=fs.readFileSync(path.join(root,rel),"utf8");vm.runInNewContext(code,{window,console});return window;}
function assert(value,message){if(!value)throw new Error(message);}
const stored=new Map();
const w={DiceboundStorage:{getString:key=>stored.get(String(key))??null,setString:(key,value)=>{stored.set(String(key),String(value));return true;}}};
load("runtime/js/classes/registry.js",w);
load("runtime/js/assets.js",w);
load("runtime/js/progression/class-unlock-rules.js",w);
load("runtime/js/progression/class-unlock-feedback.js",w);
const F=w.DiceboundClassUnlockFeedback;
assert(F,"unlock feedback owner missing");
const monolith=fs.readFileSync(path.join(root,"runtime/js/dicebound.js"),"utf8");
assert(monolith.includes("DiceboundClassUnlockFeedback?.onClassUnlocked?.(id)"),"canonical unlock path is not wired to the feedback owner");
assert(F.toastFor("cleric")==="You healed 1,000 total HP: Cleric unlocked!","Cleric toast should explain healing trigger");
assert(F.toastFor("rogue")==="You held at least 5,000 Gold at once and defeated the Board 3 miniboss: Rogue unlocked!","Rogue compound toast drifted");
assert(F.reasonFor("paladin")==="You cleared Board 3 with both Fighter and Cleric.","Paladin reason should explain both prerequisite clears");
assert(F.reasonFor("pokemontrainer")==="You raised every companion to level 10 and cleared Board 5 with Beastmaster.","Pokemon Trainer compound reason drifted");
assert(F.reasonFor("vampire")==="You exceeded 100% Lifesteal and defeated the Board 3 boss.","Vampire compound reason drifted");
assert(F.reasonFor("slimerouge")==="You unlocked Slime and cleared Board 6 with the Random class.","Slime Rouge reason drifted");
assert(F.reasonFor("dragoon")==="You defeated the Board 4 miniboss.","Dragoon fact-based unlock reason drifted");
assert(w.DiceboundClassUnlockRules.isEligible("dragoon",{facts:{board4MinibossDefeated:false}})===false,"Dragoon must remain locked before the Board 4 miniboss fact");
assert(w.DiceboundClassUnlockRules.isEligible("dragoon",{facts:{board4MinibossDefeated:true}})===true,"Dragoon must unlock from the authoritative Board 4 miniboss fact");
const cleric=F.revealFor("cleric");
assert(cleric&&cleric.name==="Cleric","Cleric reveal missing");
assert(cleric.art&&cleric.art.endsWith("/characters/classes/campsite/cleric.png"),"Cleric reveal does not use canonical class art");
assert(cleric.identity&&cleric.identity.length>20,"Cleric identity copy missing");
assert(cleric.howItPlays&&cleric.howItPlays.length>20,"Cleric gameplay copy missing");
const dragoon=F.revealFor("dragoon");
assert(dragoon&&dragoon.art&&dragoon.art.endsWith("/characters/classes/campsite/dragoon.png"),"Dragoon reveal must use its canonical full-body Camp art");
const secret=F.revealFor("bloodmage");
assert(secret.secret===true,"secret marker should be preserved after unlock");
assert(F.reasonFor("bloodmage").startsWith("You defeated"),"secret condition should only become player-facing through the post-unlock feedback path");
assert(F.onClassUnlocked("cleric").queued===true,"first class unlock should queue a reveal");
assert(F.onClassUnlocked("cleric").toast==="You healed 1,000 total HP: Cleric unlocked!","direct unlock feedback drifted");
assert(F.onClassUnlocked("cleric").queued===false,"duplicate reveal should not queue");
assert(F.state().pending.join(",")==="cleric","pending queue drifted");
F.acknowledge("cleric");
assert(F.state().pending.length===0&&F.state().acknowledged.includes("cleric"),"acknowledged reveal should persist and leave queue");
assert(F.enqueue("cleric")===false,"acknowledged reveal should not repeat");
const persisted=JSON.parse(stored.get("dicebound.class-unlock-reveals.v1"));
assert(persisted.acknowledged.includes("cleric"),"reveal acknowledgement was not persisted");
console.log("Class unlock feedback PASS: reasons, compound triggers, canonical art, queue and acknowledgement persistence");
