const fs=require("fs");const vm=require("vm");const path=require("path");
const root=path.resolve(__dirname,"..");
function load(rel,window={}){const code=fs.readFileSync(path.join(root,rel),"utf8");vm.runInNewContext(code,{window,console});return window;}
function assert(v,msg){if(!v)throw new Error(msg);}
const w=load("runtime/js/progression/class-unlock-rules.js",{}),R=w.DiceboundClassUnlockRules;
const base={petIds:["a","b"],petLevels:{a:10,b:10},highestGold:0,unlockedClassIds:[],facts:{}};
for(const mode of ["normal","nightmare","hell"]){const facts=R.recordCombatFacts({}, {board:5,finalBoss:true,classId:"beastmaster",mode});assert(R.isEligible("pokemontrainer",{...base,facts}),`Pokemon Trainer failed ${mode}`);}
let facts=R.recordCombatFacts({}, {board:3,miniBoss:true});assert(!R.isEligible("rogue",{...base,highestGold:4999,facts}),"Rogue unlocked below 5000");assert(R.isEligible("rogue",{...base,highestGold:5000,facts}),"Rogue separate facts failed");
facts=R.recordCombatFacts({}, {merchantBoss:true});assert(R.isEligible("merchant",{...base,facts}),"Merchant first kill failed");
assert(!R.isEligible("slime",{...base,unlockedClassIds:Array.from({length:9},(_,i)=>`c${i}`)}),"Slime unlocked at 9");assert(R.isEligible("slime",{...base,unlockedClassIds:Array.from({length:10},(_,i)=>`c${i}`)}),"Slime did not unlock at 10");
facts=R.recordCombatFacts({}, {board:3,finalBoss:true});facts.maxLifesteal=1;assert(!R.isEligible("vampire",{...base,facts}),"Vampire accepted exactly 100%");facts.maxLifesteal=1.001;assert(R.isEligible("vampire",{...base,facts}),"Vampire >100% failed");
let mana={};for(let i=0;i<99;i++)mana=R.recordManaSpenderCast(mana,true);mana=R.recordManaSpenderCast(mana,false);assert(!R.isEligible("invoker",{...base,facts:mana}),"Invoker counted non-spender");mana=R.recordManaSpenderCast(mana,true);assert(R.isEligible("invoker",{...base,facts:mana}),"Invoker 100 spender casts failed");
facts=R.recordCombatFacts({}, {board:4,miniBoss:true});assert(R.isEligible("dragoon",{...base,facts}),"Dragoon Board 4 miniboss failed");
const bw=load("runtime/js/powerups/borrowing.js",{}),B=bw.DiceboundPowerupBorrowing;
assert(B.ownershipAllowed({id:"generic"},"slime",["ranger"]),"generic power blocked");assert(!B.ownershipAllowed({classId:"ninja"},"slime",["ranger","fighter"]),"locked Ninja leaked to Slime");assert(B.ownershipAllowed({classId:"ninja"},"slime",["ranger","ninja"]),"unlocked Ninja unavailable to Slime");assert(B.ownershipAllowed({classIds:["ninja","fighter"]},"slime",["fighter"]),"multi-owner power failed");assert(!B.ownershipAllowed({classId:"ninja"},"slimerouge",["ranger"]),"locked Ninja leaked to Slime Rouge");
const ew={DiceboundRarities:{ids:["poor","common","uncommon","rare","epic","legendary","artifact","omega"]}};load("runtime/js/items/equipment.js",ew);const E=ew.DiceboundEquipment;
const labels={weapon:"Weapon",offhand:"Offhand",boots:"Boots",legs:"Legs",chest:"Chest",hat:"Hat",ring:"Ring",amulet:"Amulet"};for(const [slot,label] of Object.entries(labels))assert(E.ordinaryBaseName(slot)===label,`${slot} not neutral`);
const pool=[{id:"a",slots:["weapon"],tags:["ninja"]},{id:"b",slots:["weapon"],tags:["fighter"]},{id:"c",slots:["weapon"],tags:[]}];assert(E.pickOrdinaryAffix(()=>0.01,pool,"weapon").id==="a","uniform picker first");assert(E.pickOrdinaryAffix(()=>0.40,pool,"weapon").id==="b","uniform picker middle");assert(E.pickOrdinaryAffix(()=>0.90,pool,"weapon").id==="c","uniform picker last");const special=E.createRegistry().special;assert(special["axels-coffee-mug"]&&special["impossible-weapon"],"special gear was flattened");
const mono=fs.readFileSync(path.join(root,"runtime/js/dicebound.js"),"utf8");assert(mono.includes("DiceboundPowerupBorrowing.ownershipAllowed"),"borrowing helper not wired");assert(mono.includes("v318SlimeRougePowerCompatible"),"Slime Rouge compatibility owner missing");assert(mono.includes("DiceboundEquipment.pickOrdinaryAffix"),"neutral affix helper not wired");assert(!mono.includes("let n=3;if((a.tags||[]).some(t=>tags.has(t)))n+=2"),"legacy class affix weighting still live");assert(mono.includes("db0631RecordObservedProgress"),"0.6.3.1 progression wiring missing");assert(mono.includes("meta.classUnlockFacts=db0631Rules.recordCombatFacts"),"combat facts are not persisted by core career owner");assert(!mono.includes("stats.classUnlockFacts"),"class unlock facts leaked into legacy lifetime stats");const state=fs.readFileSync(path.join(root,"runtime/js/core/state.js"),"utf8");assert(state.includes("classUnlockFacts:defaultClassUnlockFacts()"),"core state does not own class unlock fact defaults");
const html=fs.readFileSync(path.join(root,"runtime/index.html"),"utf8");assert(html.includes("js/progression/class-unlock-rules.js")&&html.includes("js/powerups/borrowing.js"),"new modules not loaded");
console.log("PASS #96/#104/#87 deterministic rules");
