#!/usr/bin/env node
"use strict";
const childProcess=require("node:child_process");
const fs=require("node:fs");
const http=require("node:http");
const os=require("node:os");
const path=require("node:path");
const ROOT=path.join(__dirname,".."),RUNTIME=path.join(ROOT,"runtime");
const EDGE=process.env.DICEBOUND_EDGE||"C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe";
const DEBUG_PORT=19417;
const FIXTURE=JSON.parse(fs.readFileSync(path.join(ROOT,"tools","fixtures","merchant_stock_0_6_6_23.json"),"utf8"));
const MIME={".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".json":"application/json",".png":"image/png",".jpg":"image/jpeg",".jpeg":"image/jpeg",".webp":"image/webp",".wav":"audio/wav"};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function serveRuntime(){return new Promise((resolve,reject)=>{const server=http.createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,"http://127.0.0.1").pathname),rel=pathname==="/"?"index.html":pathname.replace(/^\/+/,""),file=path.resolve(RUNTIME,rel);if(!file.startsWith(`${RUNTIME}${path.sep}`)&&file!==path.join(RUNTIME,"index.html")){res.writeHead(403).end();return;}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404).end();return;}res.writeHead(200,{"Content-Type":MIME[path.extname(file).toLowerCase()]||"application/octet-stream","Cache-Control":"no-store"});res.end(data);});});server.once("error",reject);server.listen(0,"127.0.0.1",()=>resolve({server,url:`http://127.0.0.1:${server.address().port}/index.html`}));});}
async function waitJson(url,timeout=15000){const end=Date.now()+timeout;while(Date.now()<end){try{const r=await fetch(url);if(r.ok)return r.json();}catch(_){}await sleep(100);}throw new Error(`timeout ${url}`);}
async function connect(url){const origin=new URL(url).origin,end=Date.now()+15000;let target;while(Date.now()<end&&!target){const xs=await waitJson(`http://127.0.0.1:${DEBUG_PORT}/json/list`);target=xs.find(x=>x.type==="page"&&x.webSocketDebuggerUrl&&x.url.startsWith(origin));if(!target)await sleep(100);}if(!target)throw new Error("Edge target missing");const socket=new WebSocket(target.webSocketDebuggerUrl),pending=new Map();let id=0;await new Promise((resolve,reject)=>{socket.addEventListener("open",resolve,{once:true});socket.addEventListener("error",reject,{once:true});});socket.addEventListener("message",ev=>{const m=JSON.parse(String(ev.data)),p=pending.get(m.id);if(!p)return;pending.delete(m.id);m.error?p.reject(new Error(m.error.message)):p.resolve(m.result);});function send(method,params={}){return new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});socket.send(JSON.stringify({id:n,method,params}));});}async function evaluate(expression){const r=await send("Runtime.evaluate",{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;}return {socket,send,evaluate};}
async function main(){const profile=fs.mkdtempSync(path.join(os.tmpdir(),"dicebound-merchant-stock-probe-")),{server,url}=await serveRuntime();let child,page;try{child=childProcess.spawn(EDGE,["--headless=new","--disable-gpu","--no-sandbox","--no-first-run","--remote-allow-origins=*",`--user-data-dir=${profile}`,`--remote-debugging-port=${DEBUG_PORT}`,url],{stdio:"ignore",windowsHide:true});page=await connect(url);await page.send("Runtime.enable");const end=Date.now()+20000;while(Date.now()<end){if(await page.evaluate("document.readyState==='complete'&&!!window.DiceboundRunResumeTest&&!!window.DiceboundRng&&!!window.DiceboundBoardTileDispatch"))break;await sleep(100);}const result=await page.evaluate(`(async()=>{
  const fnv=text=>{let h=2166136261>>>0;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619);}return (h>>>0).toString(16).padStart(8,'0');};
  window.DiceboundRng.seed('merchant-stock-template');document.getElementById('campGoBtn')?.click();await new Promise(r=>setTimeout(r,250));document.getElementById('classUnlockRevealOverlay')?.classList.add('hidden');const template=window.DiceboundRunResumeTest.snapshot();
  const cases=[{name:'board1',board:1,position:11},{name:'board2',board:2,position:23},{name:'board3',board:3,position:31},{name:'board4',board:4,position:37},{name:'board5',board:5,position:43},{name:'board6',board:6,position:49},{name:'board4-free',board:4,position:37,free:true},{name:'board5-discount',board:5,position:43,discount:.25},{name:'board4-nightmare',board:4,position:37,nightmare:true},{name:'board4-hell',board:4,position:37,hell:true}];
  const outputs=[];
  for(const c of cases){const cp=structuredClone(template),idx=Math.min(c.position,cp.run.tiles.length-2);cp.run.boardLevel=c.board;cp.run.nightmareMode=!!c.nightmare;cp.run.hellMode=!!c.hell;cp.run.player.position=idx;cp.run.player.gold=99999;cp.run.player.shopDiscount=c.discount||0;cp.run.player.freeMerchantRun=!!c.free;cp.run.tiles[idx]={type:'merchant',cleared:false,packSize:1};cp.run.merchant={faceClicks:[],faceTotal:1,bossPrimed:false,bossDefeatedThisBoard:false};window.DiceboundRunResumeTest.restore(cp);await new Promise(r=>setTimeout(r,20));document.getElementById('merchantOverlay')?.classList.add('hidden');window.DiceboundRng.seed('merchant-stock-oracle:'+c.name);const before=window.DiceboundRng.snapshot();window.DiceboundBoardTileDispatch.dispatch();await new Promise(r=>setTimeout(r,60));const offers=[...document.querySelectorAll('#shopGrid .shop-item')].map(btn=>({name:btn.querySelector('.shop-item-name')?.textContent||'',desc:btn.querySelector('.shop-item-desc')?.textContent||'',price:btn.querySelector('.shop-price')?.textContent||'',comparison:btn.querySelector('.shop-compare')?.textContent||''}));const title=document.getElementById('merchantTitle')?.textContent||'',subtitle=document.getElementById('merchantSubtitle')?.textContent||'',after=window.DiceboundRng.snapshot(),signature=fnv(JSON.stringify({title,subtitle,offers}));outputs.push({name:c.name,signature,title,offerCount:offers.length,rngCalls:after.calls-before.calls,rngState:after.state});document.getElementById('merchantOverlay')?.classList.add('hidden');}
  return {version:window.DiceboundVersion?.version,cases:outputs};
})()`);const expected=FIXTURE.cases;if(JSON.stringify(result.cases)!==JSON.stringify(expected)){console.error('Merchant stock oracle mismatch.');console.error('Expected:',JSON.stringify(expected,null,2));console.error('Actual:',JSON.stringify(result.cases,null,2));throw new Error('Merchant stock/output/RNG contract changed.');}console.log(`Merchant stock oracle passed: ${result.cases.length} cases match released ${FIXTURE.sourceVersion} signatures and exact RNG state.`);}finally{try{await page?.send("Browser.close");}catch(_){}try{page?.socket.close();}catch(_){}if(child?.exitCode===null)child.kill();await new Promise(r=>server.close(r));try{fs.rmSync(profile,{recursive:true,force:true});}catch(_){}}}
main().catch(e=>{console.error(e);process.exitCode=1;});
