#!/usr/bin/env node
"use strict";
const childProcess=require("node:child_process"),fs=require("node:fs"),http=require("node:http"),os=require("node:os"),path=require("node:path");
const ROOT=path.join(__dirname,".."),RUNTIME=path.join(ROOT,"runtime"),EDGE=process.env.DICEBOUND_EDGE||"C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe",DEBUG_PORT=Number(process.env.DICEBOUND_CLASSES_DEBUG_PORT||19435),sleep=ms=>new Promise(r=>setTimeout(r,ms));
const MIME={".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".json":"application/json",".png":"image/png",".jpg":"image/jpeg",".jpeg":"image/jpeg",".webp":"image/webp",".wav":"audio/wav"};
function serve(){return new Promise((resolve,reject)=>{const server=http.createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,"http://127.0.0.1").pathname),rel=pathname==="/"?"index.html":pathname.replace(/^\/+/,""),file=path.resolve(RUNTIME,rel);if(!file.startsWith(`${RUNTIME}${path.sep}`)&&file!==path.join(RUNTIME,"index.html")){res.writeHead(403).end();return;}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404).end();return;}res.writeHead(200,{"Content-Type":MIME[path.extname(file).toLowerCase()]||"application/octet-stream","Cache-Control":"no-store"});res.end(data);});});server.once("error",reject);server.listen(0,"127.0.0.1",()=>resolve({server,url:`http://127.0.0.1:${server.address().port}/index.html`}));});}
async function waitJson(url){const end=Date.now()+15000;while(Date.now()<end){try{const r=await fetch(url);if(r.ok)return r.json();}catch{}await sleep(100);}throw new Error("debug target timeout");}
async function main(){const profile=fs.mkdtempSync(path.join(os.tmpdir(),"dicebound-class-surface-")),{server,url}=await serve();let child,socket;try{child=childProcess.spawn(EDGE,["--headless=new","--disable-gpu","--no-sandbox","--no-first-run","--remote-allow-origins=*",`--user-data-dir=${profile}`,`--remote-debugging-port=${DEBUG_PORT}`,url],{stdio:"ignore",windowsHide:true});const origin=new URL(url).origin;let target;for(let i=0;i<100&&!target;i++){const list=await waitJson(`http://127.0.0.1:${DEBUG_PORT}/json/list`);target=list.find(x=>x.type==="page"&&x.webSocketDebuggerUrl&&x.url.startsWith(origin));if(!target)await sleep(100);}if(!target)throw new Error("Edge target missing");socket=new WebSocket(target.webSocketDebuggerUrl);await new Promise((r,j)=>{socket.addEventListener("open",r,{once:true});socket.addEventListener("error",j,{once:true});});let id=0;const pending=new Map(),errors=[],consoleLines=[];socket.addEventListener("message",ev=>{const m=JSON.parse(String(ev.data));if(m.id){const p=pending.get(m.id);if(p){pending.delete(m.id);m.error?p.reject(new Error(m.error.message)):p.resolve(m.result);}return;}if(m.method==="Runtime.exceptionThrown")errors.push(m.params.exceptionDetails?.exception?.description||m.params.exceptionDetails?.text||JSON.stringify(m.params));if(m.method==="Runtime.consoleAPICalled")consoleLines.push((m.params.args||[]).map(x=>x.value??x.description).join(" "));});const send=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});socket.send(JSON.stringify({id:n,method,params}));});await send("Runtime.enable");await send("Console.enable").catch(()=>{});await sleep(5000);const evalResult=await send("Runtime.evaluate",{expression:`(()=>({readyState:document.readyState,flags:{RunResume:!!window.DiceboundRunResumeTest,Progression:!!window.DiceboundProgressionOracleTest,ClassesOracle:!!window.DiceboundClassesOracleTest,Classes:!!window.DiceboundClasses,Rng:!!window.DiceboundRng,V318:!!window.DiceboundV318Test,Beta021:!!window.DiceboundBeta021Test},version:window.DiceboundVersion?.version||null}))()`,returnByValue:true});console.log("SURFACE",JSON.stringify(evalResult.result?.value));console.log("EXCEPTIONS",JSON.stringify(errors,null,2));console.log("CONSOLE",JSON.stringify(consoleLines.slice(-30),null,2));if(errors.length)process.exitCode=2;}finally{try{socket?.close();}catch{}try{child?.kill();}catch{}await new Promise(r=>server.close(r));try{fs.rmSync(profile,{recursive:true,force:true});}catch{}}}
main().catch(e=>{console.error(e.stack||e);process.exitCode=1;});
